"use client";
import { useState } from "react";
import { PRIVACY } from "../lib/data/privacy.js";

const TERMS_LANGS = ["nl","en","de","fr","es"];

// TERMS inline (same 5 langs)
const TERMS = {
  nl:{title:"Algemene Voorwaarden – Untangle™",updated:"Laatst bijgewerkt: 2026",intro:"Deze algemene voorwaarden zijn van toepassing op het gebruik van de app en website Untangle™ (www.untangle.lol). Door de app of website te gebruiken ga je akkoord met deze voorwaarden.",sections:[{heading:"1. Over Untangle",body:"Untangle is een digitale applicatie die gebruikers helpt bij het structureren van doelen, het identificeren van obstakels en het plannen van stappen richting persoonlijke of professionele doelstellingen."},{heading:"2. Gebruik van de dienst",body:"Gebruikers mogen Untangle alleen gebruiken voor legitieme doeleinden. Het is niet toegestaan om:",list:["de app te misbruiken of te manipuleren","de werking van de app te verstoren","de app te gebruiken voor illegale activiteiten","systemen van Untangle te proberen te hacken of te omzeilen"]},{heading:"3. Accounts",body:"Voor sommige functies kan een account vereist zijn. Gebruikers zijn verantwoordelijk voor het veilig houden van hun accountgegevens en wachtwoorden."},{heading:"4. Intellectueel eigendom",body:"Alle inhoud, technologie, software, logo's, ontwerpen en functionaliteiten van Untangle zijn beschermd door intellectuele eigendomsrechten. Zonder schriftelijke toestemming mogen deze niet worden gekopieerd, verspreid of commercieel gebruikt."},{heading:"5. Beschikbaarheid van de dienst",body:"Wij streven ernaar om de app continu beschikbaar te houden, maar kunnen geen ononderbroken beschikbaarheid garanderen."},{heading:"6. Aansprakelijkheid",body:"Untangle is een hulpmiddel voor persoonlijke organisatie en doelplanning. Wij zijn niet aansprakelijk voor directe of indirecte schade die voortvloeit uit het gebruik van de app of website."},{heading:"7. Privacy",body:"Het gebruik van persoonsgegevens wordt geregeld in onze Privacy Policy."},{heading:"8. Beëindiging",body:"Wij behouden ons het recht voor om accounts te beperken of te beëindigen wanneer gebruikers deze voorwaarden schenden."},{heading:"9. Wijzigingen",body:"Untangle kan deze voorwaarden van tijd tot tijd aanpassen. De meest actuele versie is altijd beschikbaar op www.untangle.lol."},{heading:"10. Toepasselijk recht",body:"Op deze voorwaarden is het recht van toepassing van het land waar de dienst wordt geëxploiteerd."},{heading:"11. Contact",body:"Voor vragen over deze voorwaarden kun je contact opnemen via:",contact:"www.untangle.lol"}],back:"Terug"},
  en:{title:"Terms & Conditions – Untangle™",updated:"Last updated: 2026",intro:"These terms and conditions apply to the use of the Untangle™ app and website (www.untangle.lol). By using the app or website you agree to these terms.",sections:[{heading:"1. About Untangle",body:"Untangle is a digital application that helps users structure goals, identify obstacles, and plan steps towards personal or professional objectives."},{heading:"2. Use of the service",body:"Users may only use Untangle for legitimate purposes. The following are not permitted:",list:["misusing or manipulating the app","disrupting the operation of the app","using the app for illegal activities","attempting to hack or circumvent Untangle's systems"]},{heading:"3. Accounts",body:"Some features may require an account. Users are responsible for keeping their account credentials and passwords secure."},{heading:"4. Intellectual property",body:"All content, technology, software, logos, designs and functionalities of Untangle are protected by intellectual property rights."},{heading:"5. Service availability",body:"We strive to keep the app continuously available but cannot guarantee uninterrupted availability."},{heading:"6. Liability",body:"Untangle is a tool for personal organisation and goal planning. We are not liable for direct or indirect damages arising from use of the app or website."},{heading:"7. Privacy",body:"The use of personal data is governed by our Privacy Policy."},{heading:"8. Termination",body:"We reserve the right to restrict or terminate accounts when users violate these terms or misuse the service."},{heading:"9. Changes",body:"Untangle may update these terms from time to time. The most current version will always be available at www.untangle.lol."},{heading:"10. Applicable law",body:"These terms are governed by the law of the country in which the service is operated."},{heading:"11. Contact",body:"For questions about these terms you can reach us at:",contact:"www.untangle.lol"}],back:"Back"},
  de:{title:"Allgemeine Geschäftsbedingungen – Untangle™",updated:"Zuletzt aktualisiert: 2026",intro:"Diese allgemeinen Geschäftsbedingungen gelten für die Nutzung der App und Website Untangle™ (www.untangle.lol).",sections:[{heading:"1. Über Untangle",body:"Untangle ist eine digitale Anwendung, die Nutzern hilft, Ziele zu strukturieren, Hindernisse zu identifizieren und Schritte zu planen."},{heading:"2. Nutzung des Dienstes",body:"Nutzer dürfen Untangle nur für legitime Zwecke verwenden. Folgendes ist nicht gestattet:",list:["die App zu missbrauchen oder zu manipulieren","den Betrieb der App zu stören","die App für illegale Aktivitäten zu nutzen","die Systeme von Untangle zu hacken"]},{heading:"3. Konten",body:"Nutzer sind verantwortlich für die sichere Aufbewahrung ihrer Kontodaten."},{heading:"4. Geistiges Eigentum",body:"Alle Inhalte und Funktionalitäten von Untangle sind durch Rechte des geistigen Eigentums geschützt."},{heading:"5. Verfügbarkeit",body:"Wir streben an, die App verfügbar zu halten, können jedoch keine ununterbrochene Verfügbarkeit garantieren."},{heading:"6. Haftung",body:"Wir haften nicht für direkte oder indirekte Schäden aus der Nutzung der App."},{heading:"7. Datenschutz",body:"Die Verwendung personenbezogener Daten wird in unserer Datenschutzrichtlinie geregelt."},{heading:"8. Kündigung",body:"Wir behalten uns das Recht vor, Konten einzuschränken wenn Nutzer gegen diese Bedingungen verstoßen."},{heading:"9. Änderungen",body:"Untangle kann diese Bedingungen anpassen. Die aktuelle Version ist unter www.untangle.lol verfügbar."},{heading:"10. Anwendbares Recht",body:"Für diese Bedingungen gilt das Recht des Landes, in dem der Dienst betrieben wird."},{heading:"11. Kontakt",body:"Bei Fragen kannst du uns kontaktieren über:",contact:"www.untangle.lol"}],back:"Zurück"},
  fr:{title:"Conditions Générales d'Utilisation – Untangle™",updated:"Dernière mise à jour : 2026",intro:"Les présentes conditions générales s'appliquent à l'utilisation de l'application et du site web Untangle™ (www.untangle.lol).",sections:[{heading:"1. À propos d'Untangle",body:"Untangle est une application numérique qui aide les utilisateurs à structurer leurs objectifs et planifier des étapes."},{heading:"2. Utilisation du service",body:"Les utilisateurs ne peuvent utiliser Untangle qu'à des fins légitimes. Il est interdit de :",list:["abuser ou manipuler l'application","perturber le fonctionnement de l'application","utiliser l'application à des fins illégales","tenter de pirater les systèmes d'Untangle"]},{heading:"3. Comptes",body:"Les utilisateurs sont responsables de la sécurité de leurs identifiants."},{heading:"4. Propriété intellectuelle",body:"Tous les contenus et fonctionnalités d'Untangle sont protégés par des droits de propriété intellectuelle."},{heading:"5. Disponibilité",body:"Nous nous efforçons de maintenir l'application disponible mais ne pouvons garantir une disponibilité ininterrompue."},{heading:"6. Responsabilité",body:"Nous ne sommes pas responsables des dommages découlant de l'utilisation de l'application."},{heading:"7. Confidentialité",body:"L'utilisation des données personnelles est régie par notre Politique de confidentialité."},{heading:"8. Résiliation",body:"Nous nous réservons le droit de restreindre des comptes en cas de violation de ces conditions."},{heading:"9. Modifications",body:"Untangle peut mettre à jour ces conditions. La version la plus récente est disponible sur www.untangle.lol."},{heading:"10. Droit applicable",body:"Ces conditions sont régies par le droit du pays dans lequel le service est exploité."},{heading:"11. Contact",body:"Pour toute question, vous pouvez nous contacter via :",contact:"www.untangle.lol"}],back:"Retour"},
  es:{title:"Términos y Condiciones – Untangle™",updated:"Última actualización: 2026",intro:"Estos términos y condiciones se aplican al uso de la aplicación y sitio web Untangle™ (www.untangle.lol).",sections:[{heading:"1. Sobre Untangle",body:"Untangle es una aplicación digital que ayuda a los usuarios a estructurar objetivos y planificar pasos."},{heading:"2. Uso del servicio",body:"Los usuarios solo pueden usar Untangle para fines legítimos. No está permitido:",list:["abusar o manipular la aplicación","interrumpir el funcionamiento de la aplicación","usar la aplicación para actividades ilegales","intentar hackear los sistemas de Untangle"]},{heading:"3. Cuentas",body:"Los usuarios son responsables de mantener seguros sus credenciales."},{heading:"4. Propiedad intelectual",body:"Todos los contenidos y funcionalidades de Untangle están protegidos por derechos de propiedad intelectual."},{heading:"5. Disponibilidad",body:"Nos esforzamos por mantener la aplicación disponible pero no podemos garantizar disponibilidad ininterrumpida."},{heading:"6. Responsabilidad",body:"No somos responsables de daños derivados del uso de la aplicación."},{heading:"7. Privacidad",body:"El uso de datos personales se rige por nuestra Política de Privacidad."},{heading:"8. Terminación",body:"Nos reservamos el derecho de cancelar cuentas cuando los usuarios violen estos términos."},{heading:"9. Cambios",body:"Untangle puede actualizar estos términos. La versión actual estará en www.untangle.lol."},{heading:"10. Ley aplicable",body:"Estos términos se rigen por la ley del país en el que opera el servicio."},{heading:"11. Contacto",body:"Para preguntas puedes contactarnos en:",contact:"www.untangle.lol"}],back:"Volver"},
};

export default function LegalView({ type, lang, c, sx, t, dir, onBack, onSwitch }) {
  const fallback = TERMS_LANGS.includes(lang) ? lang : "en";
  const [viewLang, setViewLang] = useState(fallback);
  const DATA = type === "privacy" ? PRIVACY : TERMS;
  const d = DATA[viewLang] || DATA.en;

  return (
    <div dir={dir} style={{...sx.pg,paddingTop:"calc(64px + env(safe-area-inset-top))"}}><div className="uw" style={sx.w}>
      {/* Lang switcher */}
      <div style={{display:"flex",gap:6,marginBottom:14,flexWrap:"wrap"}}>
        {TERMS_LANGS.map(l=>(
          <button key={l} onClick={()=>setViewLang(l)} style={{padding:"3px 10px",borderRadius:20,fontSize:11,fontWeight:700,background:l===viewLang?c.ab:"transparent",color:l===viewLang?c.ac:c.tf,border:"1px solid "+(l===viewLang?c.abr:c.cb),cursor:"pointer",letterSpacing:"0.05em",fontFamily:"inherit"}}>
            {l.toUpperCase()}
          </button>
        ))}
      </div>
      <div style={sx.cd}>
        <h1 style={{fontSize:17,fontWeight:800,color:c.tx,margin:"0 0 3px",letterSpacing:"-0.02em"}}>{d.title}</h1>
        <p style={{fontSize:11,color:c.tf,margin:"0 0 14px"}}>{d.updated}</p>
        <p style={{fontSize:13,color:c.tm,lineHeight:1.7,margin:"0 0 20px",paddingBottom:16,borderBottom:"1px solid "+c.cb}}>{d.intro}</p>
        <div style={{display:"flex",flexDirection:"column",gap:16}}>
          {d.sections.map((s,i)=>(
            <div key={i}>
              <h2 style={{fontSize:13,fontWeight:700,color:c.tx,margin:"0 0 5px"}}>{s.heading}</h2>
              <p style={{fontSize:13,color:c.tm,lineHeight:1.7,margin:0}}>{s.body}</p>
              {s.list&&<ul style={{margin:"6px 0 0",paddingLeft:16}}>{s.list.map((item,j)=><li key={j} style={{fontSize:12,color:c.tm,lineHeight:1.7,marginBottom:2}}>{item}</li>)}</ul>}
              {s.after&&<p style={{marginTop:7,fontSize:12,color:c.tm}}>{s.after}</p>}
              {s.contact&&<p style={{marginTop:5,fontSize:12}}><a href="https://untangle.lol" style={{color:c.ac,textDecoration:"none"}}>untangle.lol</a></p>}
            </div>
          ))}
        </div>
      </div>
      <div style={{display:"flex",gap:8,marginTop:4}}>
        <button onClick={onBack} style={sx.bg}><span style={{display:"flex",alignItems:"center",gap:5,justifyContent:"center"}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{display:"block",flexShrink:0}}><path d="M19 12H5"/><polyline points="12 19 5 12 12 5"/></svg>{t.back||"Back"}</span></button>
        {onSwitch&&<button onClick={onSwitch} style={{...sx.bg,flex:1,marginTop:12}}>{type==="privacy"?(t.terms||"Terms"):(t.privacy||"Privacy")}</button>}
      </div>
    </div></div>
  );
}
