const en = {
  code:"en",label:"English",flag:"🇬🇧",
  ph:"Start typing...",
  hero:"What do you want to achieve?",
  heroS:["Just type it in.","No question is too weird.","Big or small — anything goes.","What's on your mind?","Write it down, we'll help you figure it out."],
  go:"Let's begin →",back:"← Back",out:"Log out",clr:"🗑️ Clear all",nG:"➕ New goal",noG:"No goals yet. Time to begin!",
  prog:"progress",allD:"🎉 All done!",sOf:"of",
  eth:"🌍 Advice with respect for people, planet & wellbeing",
  err:"Oops, try again!",resB:"← Back to overview",dW:"Welcome back",dS:"Here are your goals.",
  byok:"Enter your API key",byokH1:"Bring your own API key",chAuth:"Change auth",rmKey:"Remove key",lSel:"Language",
  byokL:"API Key (Anthropic or OpenRouter)",byokPh:"sk-ant-... or sk-or-...",byokSave:"Save & continue",
  byokNote:"Stored in your browser only. Never shared.",
  apiKeyBadge:"🔑 API Key",apiKeyUnset:"set",checking:"Checking...",chooseLang:"Choose your language",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Direct access to Claude. Keys start with",
  byokAnthS1:"Go to console.anthropic.com",byokAnthS2:"Sign up / log in",byokAnthS3:"Settings → API Keys → Create key",byokAnthLink:"Get Anthropic key →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Pay-as-you-go. Often cheaper. Keys start with",
  byokOrS1:"Go to openrouter.ai",byokOrS2:"Sign up / log in",byokOrS3:"Keys → Create key",byokOrLink:"Get OpenRouter key →",
  keyErrFmt:"Key should start with sk-ant- or sk-or-",keyErrInv:"Invalid key: ",keyErrNet:"Could not reach API to verify — key saved anyway.",
  usageStat:"Usage stats",apiCalls:"API calls",estCost:"Est. cost",inputTok:"Input tokens",outputTok:"Output tokens",resetStats:"Reset stats",
  rmTip:"Remove",start:"Start",cred:"credits",credFree:"free credits",credOut:"Out of credits",
  credOutMsg:"Your free credits are used up. Add your own API key to keep going — free to get from Anthropic or OpenRouter.",
  credByok:"Add your own key →",
  lp:["🧠 Thinking...","☕ Brewing ideas...","🔮 Crystal ball warming up...","🧙 Casting spells...","🤔 Deep thought...","🎯 Locking in..."],
  topUp:"Top up credits",topUpDesc:"10 credits for €2.50",topUpBtn:"Pay with Stripe →",
  topUpSuccess:"Payment successful! Credits will be added shortly.",topUpPending:"Processing credits...",
  topUpPopupTitle:"Credits added! 🎉",
  topUpPopupMsg:"untangle.lol is free and private — no ads, no data harvesting. Credits keep the AI running and support a fair, independent product. Thank you for your support!",
  topUpPopupBtn:"Great, let's go!",
  altruismPopupTitle:"How kind of you! 💛",
  altruismPopupMsg:"Your goal is about helping others — like volunteering, caregiving, or supporting a good cause. That deserves a reward: complete all steps and automatically earn 3 free credits!",
  altruismPopupBtn:"Great, let's go!",
  altruismBonusTitle:"🎁 +3 credits earned!",
  altruismBonusMsg:"Congratulations! You completed your altruistic goal. As a thank-you for your efforts to help others, we've added 3 free credits to your account.",
  altruismBonusBtn:"Awesome, thank you!",
  altruismTeaser:"💛 Do something for others and earn 3 free credits.",
  altruismPopupMsgRepeat:"Your goal is about helping others — which is truly wonderful. Complete all the steps and make a real difference!",
  analyticsNote:"We collect anonymous usage statistics (no cookies, no personal data).",
  signIn:"Sign in with Google",signInSub:"Save your goals across all devices",signOut:"Sign out",
  profile:"Profile",terms:"Terms",privacy:"Privacy",stats:"Stats",donate:"❤️ Donate",donateMsg:"❤️ Your donation makes the world a little better",revenue:"Revenue",revTotal:"Total income",revEmpty:"No transactions yet.",revMore:"Load more",
  share:"Share",shareCopy:"Copy",shareCopied:"Copied!",shareMsg:"Check out my action plan on untangle.lol:",
  altruismLoadingMsg:"💛 You're doing something wonderful for others.",
  altruisticSugg:["I want to volunteer at a food bank","I want to become a caregiver for a family member","I want to mentor a young person","I want to donate blood regularly","I want to start a community garden","I want to organize a charity fundraiser","I want to help elderly neighbors","I want to volunteer at an animal shelter","I want to raise awareness about climate change","I want to help adults learn to read"],
  phSugg:["I want to sleep better","I want to learn guitar","I want to exercise every day","I want to write a book","I want to eat healthier","I want to learn a new language","I want to spend less time on social media","I want to start my own business","I want to spend more time with my family","I want to meditate every morning","I want to pay off my debt","I want to run a marathon","I want to learn to cook","I want to find a new job","I want to save more money"],
  woop:"🎯 Try WOOP",woopOr:"or",woopTitle:"WOOP Method",
  woopSub:"A proven technique to turn wishes into action — step by step.",
  woopLabels:["Wish","Outcome","Obstacle","Plan"],
  woopHints:[
    "What do you really want? Pick something that touches your heart — challenging but achievable.",
    "Imagine the best possible result. How do you feel when your wish comes true?",
    "What is the main inner obstacle — a habit, feeling, or thought — that could hold you back?",
    "If [obstacle], then I will [action]. Make a specific if-then plan.",
  ],
  woopPh:[
    "E.g. 'I want to exercise every morning'",
    "E.g. 'I feel energised and proud of myself'",
    "E.g. 'I snooze my alarm because I'm tired'",
    "E.g. 'If I snooze my alarm, I will lay out my gym clothes the night before'",
  ],
  woopGo:"Create my plan →",woopLink:"Learn about the science",woopSummaryTitle:"Your WOOP",
  suggLabel:"💡 Pick a suggestion",
  taClrConfirm:"clear?",
  celebTitle:"Congratulations! 🎉",
  celebMsg:"You've completed every step. Well done — this calls for a celebration!",
  celebBtn:"Thank you!",
  fbTitle:"Feedback",fbPh:"Something broken or a suggestion? Tell us…",fbSend:"Send",fbCancel:"Cancel",fbSent:"Received, thanks!",fbErr:"Failed — try again",fbHint:"⌘↵ to send",
  dyslexia:"Dyslexia-friendly font",
  braille:"Braille font",
};
export default en;
