const es = {
  code:"es",label:"Español",flag:"🇪🇸",
  ph:"Empieza a escribir...",
  hero:"¿Qué quieres lograr?",heroLabel:"Escribe aquí lo que tienes en mente",
  heroS:["Solo escríbelo.","Ninguna pregunta es demasiado rara.","Grande o pequeño — todo vale.","¿Qué tienes en mente?","Escríbelo, te ayudamos a seguir adelante."],
  go:"Comencemos →",back:"← Volver",out:"Salir",clr:"🗑️ Borrar",nG:"➕ Nueva meta",noG:"Sin metas. ¡Hora de comenzar!",
  prog:"progreso",allD:"🎉 ¡Listo!",sOf:"de",
  eth:"🌍 Consejos con respeto",
  err:"¡Ups!",resB:"← Volver",dW:"Hola de nuevo",dS:"Tus metas.",
  byok:"Ingresar clave API",byokH1:"Usa tu propia clave API",chAuth:"Cambiar auth",rmKey:"Eliminar clave",lSel:"Idioma",
  byokL:"Clave API (Anthropic u OpenRouter)",byokPh:"sk-ant-... o sk-or-...",byokSave:"Guardar",
  byokNote:"Guardada en tu navegador. Nunca compartida.",
  apiKeyBadge:"🔑 Clave API",apiKeyUnset:"configurar",checking:"Comprobando...",chooseLang:"Elige tu idioma",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Acceso directo a Claude. Las claves empiezan con",
  byokAnthS1:"Ir a console.anthropic.com",byokAnthS2:"Registrarse / iniciar sesión",byokAnthS3:"Ajustes → Claves API → Crear clave",byokAnthLink:"Obtener clave de Anthropic →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Pago por uso. A menudo más barato. Las claves empiezan con",
  byokOrS1:"Ir a openrouter.ai",byokOrS2:"Registrarse / iniciar sesión",byokOrS3:"Claves → Crear clave",byokOrLink:"Obtener clave de OpenRouter →",
  keyErrFmt:"La clave debe empezar con sk-ant- o sk-or-",keyErrInv:"Clave inválida: ",keyErrNet:"No se pudo verificar con la API — clave guardada de todas formas.",
  usageStat:"Estadísticas de uso",apiCalls:"Llamadas API",estCost:"Coste estimado",inputTok:"Tokens de entrada",outputTok:"Tokens de salida",resetStats:"Resetear stats",
  rmTip:"Eliminar",start:"Empezar",cred:"preguntas",credFree:"preguntas gratis",credOut:"Sin preguntas",
  credOutMsg:"Tus preguntas gratuitas se agotaron. Agrega tu propia clave API para continuar — gratis en Anthropic u OpenRouter.",
  credByok:"Agregar mi clave →",
  lp:["🧠 Pensando...","☕ Destilando ideas...","🔮 Calentando la bola de cristal...","🧙 Lanzando hechizos...","🤔 Reflexionando...","🎯 Enfocando..."],
  topUp:"Recargar preguntas",topUpDesc:"10 preguntas por €2,50",topUpBtn:"Pagar con Stripe →",
  topUpSuccess:"¡Pago exitoso! Las preguntas se añadirán pronto.",topUpPending:"Procesando preguntas...",
  topUpPopupTitle:"¡Preguntas añadidas! 🎉",
  topUpPopupMsg:"untangle.lol es gratuito y privado — sin anuncios ni recopilación de datos. Las preguntas mantienen la IA en marcha y apoyan un producto justo e independiente. ¡Gracias!",
  topUpPopupBtn:"¡Genial, a por ello!",
  altruismPopupTitle:"¡Qué amable eres! 💛",
  altruismPopupMsg:"Tu meta consiste en ayudar a otros — como voluntariado, cuidado de personas o apoyo a una buena causa. Eso merece una recompensa: completa todos los pasos y gana automáticamente 2 preguntas gratis.",
  altruismPopupBtn:"¡Genial, a por ello!",
  altruismBonusTitle:"🎁 ¡+2 preguntas ganadas!",
  altruismBonusMsg:"¡Felicitaciones! Completaste tu meta altruista. Como agradecimiento por tu esfuerzo para ayudar a otros, hemos añadido 2 preguntas gratuitas a tu cuenta.",
  altruismBonusBtn:"¡Increíble, gracias!",
  altruismTeaser:"💡 Haz algo por los demás y gana 2 preguntas gratis.",
  altruismPopupMsgRepeat:"Tu meta consiste en ayudar a otros — eso es realmente maravilloso. ¡Completa todos los pasos y marca la diferencia!",
  analyticsNote:"Recopilamos estadísticas de uso anónimas (sin cookies ni datos personales).",
  signIn:"Iniciar sesión con Google",signInSub:"Guarda tus metas en todos tus dispositivos",signOut:"Cerrar sesión",
  profile:"Perfil",terms:"Términos",privacy:"Privacidad",stats:"Estadísticas",donate:"❤️ Donar",donateMsg:"❤️ Tu donación contribuye a un mundo mejor",revenue:"Ingresos",revTotal:"Ingresos totales",revEmpty:"Sin transacciones aún.",revMore:"Cargar más",
  share:"Compartir",shareCopy:"Copiar",shareCopied:"¡Copiado!",shareMsg:"Mira mi plan de acción en untangle.lol:",
  altruismLoadingMsg:"💛 Estás haciendo algo maravilloso por los demás.",
  altruisticSugg:["Quiero hacer voluntariado en un banco de alimentos","Quiero cuidar a un familiar","Quiero crear un huerto comunitario","Quiero donar sangre regularmente","Quiero ser mentor de un joven","Quiero organizar una campaña benéfica","Quiero ayudar a personas mayores en mi barrio","Quiero hacer voluntariado en un refugio de animales","Quiero concienciar sobre el cambio climático","Quiero enseñar a leer a adultos"],
  phSugg:["Quiero dormir mejor","Quiero aprender guitarra","Quiero hacer ejercicio cada día","Quiero escribir un libro","Quiero comer más sano","Quiero aprender un nuevo idioma","Quiero usar menos las redes sociales","Quiero iniciar mi propio negocio","Quiero pasar más tiempo con mi familia","Quiero meditar cada mañana","Quiero saldar mis deudas","Quiero correr un maratón","Quiero aprender a cocinar","Quiero encontrar un nuevo trabajo","Quiero ahorrar más dinero"],
  woop:"🎯 Probar WOOP",woopOr:"o",woopTitle:"Método WOOP",
  woopSub:"Una técnica probada para convertir deseos en acciones — paso a paso.",
  woopLabels:["Deseo","Resultado","Obstáculo","Plan"],
  woopHints:[
    "¿Qué deseas realmente? Elige algo significativo — desafiante pero alcanzable.",
    "Imagina el mejor resultado posible. ¿Cómo te sientes cuando tu deseo se hace realidad?",
    "¿Cuál es el principal obstáculo interno — un hábito, sentimiento o pensamiento — que podría frenarte?",
    "Si [obstáculo], entonces haré [acción]. Crea un plan concreto si-entonces.",
  ],
  woopPh:[
    "Ej. 'Quiero hacer ejercicio cada mañana'",
    "Ej. 'Me siento lleno de energía y orgulloso de mí mismo'",
    "Ej. 'Apago la alarma porque estoy cansado'",
    "Ej. 'Si apago la alarma, prepararé mi ropa de deporte la noche anterior'",
  ],
  woopGo:"Crear mi plan →",woopLink:"Más sobre la ciencia",woopSummaryTitle:"Tu WOOP",
  suggLabel:"¿No sabes qué escribir? Elige una sugerencia",
  taClrConfirm:"¿borrar?",
  celebTitle:"¡Felicitaciones! 🎉",
  celebMsg:"Has completado todos los pasos. ¡Bien hecho — esto merece una celebración!",
  celebBtn:"¡Gracias!",
  fbTitle:"Comentarios",fbPh:"¿Algo roto o una sugerencia? Cuéntanos…",fbSend:"Enviar",fbCancel:"Cancelar",fbSent:"¡Recibido, gracias!",fbErr:"Falló — inténtalo de nuevo",fbHint:"⌘↵ para enviar",
  dyslexia:"Fuente para dislexia",
  braille:"Fuente Braille",
};
export default es;
