const fr = {
  code:"fr",label:"Français",flag:"🇫🇷",
  ph:"Commencez à taper...",
  hero:"Que veux-tu accomplir ?",heroLabel:"Écris ici ce qui t'occupe l'esprit",
  heroS:["Tape-le.","Aucune question n'est trop bizarre.","Grand ou petit — tout est permis.","Qu'est-ce qui t'occupe l'esprit ?","Écris-le, on t'aide à avancer."],
  go:"Commençons →",back:"Retour",out:"Déco",clr:"Effacer",nG:"Nouveau",noG:"Pas d'objectifs. On commence !",
  prog:"progrès",allD:"Fini !",sOf:"de",
  eth:"Conseils respectueux",
  err:"Oups !",resB:"← Retour",dW:"Re-bonjour",dS:"Tes objectifs.",
  byok:"Entrer la clé API",byokH1:"Utilise ta propre clé API",chAuth:"Changer auth",rmKey:"Supprimer clé",lSel:"Langue",
  byokL:"Clé API (Anthropic ou OpenRouter)",byokPh:"sk-ant-... ou sk-or-...",byokSave:"Enregistrer",
  byokNote:"Stockée dans ton navigateur. Jamais partagée.",
  apiKeyBadge:"Clé API",apiKeyUnset:"définir",checking:"Vérification...",chooseLang:"Choisis ta langue",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Accès direct à Claude. Les clés commencent par",
  byokAnthS1:"Aller sur console.anthropic.com",byokAnthS2:"S'inscrire / se connecter",byokAnthS3:"Paramètres → Clés API → Créer une clé",byokAnthLink:"Obtenir une clé Anthropic →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Pay-as-you-go. Souvent moins cher. Les clés commencent par",
  byokOrS1:"Aller sur openrouter.ai",byokOrS2:"S'inscrire / se connecter",byokOrS3:"Clés → Créer une clé",byokOrLink:"Obtenir une clé OpenRouter →",
  keyErrFmt:"La clé doit commencer par sk-ant- ou sk-or-",keyErrInv:"Clé invalide : ",keyErrNet:"API inaccessible — clé sauvegardée quand même.",
  usageStat:"Statistiques d'utilisation",apiCalls:"Appels API",estCost:"Coût estimé",inputTok:"Tokens en entrée",outputTok:"Tokens en sortie",resetStats:"Réinitialiser",
  rmTip:"Supprimer",start:"Démarrer",cred:"questions",credFree:"questions gratuites",credOut:"Plus de questions",
  credOutMsg:"Tes questions gratuites sont épuisées. Ajoute ta propre clé API pour continuer — gratuite chez Anthropic ou OpenRouter.",
  credByok:"Ajouter ma clé →",
  lp:["Réflexion...","Brassage d'idées...","Boule de cristal en chauffe...","Sorts en cours...","Pensée profonde...","Concentration..."],
  topUpDesc:"10 questions pour €2,50",topUpBtn:"Payer avec Stripe →",
  topUpSuccess:"Paiement réussi ! Les questions seront ajoutées sous peu.",topUpPending:"Traitement des questions...",
  topUpPopupTitle:"Questions ajoutées !",
  topUpPopupMsg:"untangle.lol est gratuit et privé — sans pub ni collecte de données. Les questions font tourner l'IA et soutiennent un produit équitable et indépendant. Merci !",
  topUpPopupBtn:"Super, c'est parti !",
  altruismPopupTitle:"Comme c'est gentil !",
  altruismPopupMsg:"Ton objectif est pour les autres — partage ton plan et gagne 2 questions gratuites.",
  altruismPopupBtn:"Partager le plan →",
  altruismBonusTitle:"+{n} questions gagnées !",altruismBonusTitleSg:"+1 question gagnée !",
  altruismBonusMsg:"Tu as partagé ton plan ! En guise de merci, voici 2 questions gratuites.",
  altruismBonusBtn:"Super, merci !",
  altruismTeaser:"Partage un plan pour les autres et gagne 2 questions gratuites.",
  altruismPopupMsgRepeat:"Ton objectif aide les autres — super ! Partage ton plan et inspire quelqu'un.",
  altruismShareCta:"Partage ce plan et gagne +2 questions gratuites",
  analyticsNote:"Nous collectons des statistiques d'utilisation anonymes (sans cookies ni données personnelles).",
  signIn:"Se connecter",signInSub:"Sauvegarde tes objectifs sur tous tes appareils",signOut:"Déconnexion",
  profile:"Profil",terms:"CGU",privacy:"Confidentialité",stats:"Statistiques",donate:"Faire un don",donateMsg:"Votre don contribue à un monde meilleur",revenue:"Revenus",revTotal:"Total des revenus",revEmpty:"Aucune transaction pour l'instant.",revMore:"Charger plus",
  share:"Partager",shareCopy:"Copier",shareCopied:"Copié !",shareMsg:"Découvre mon plan d'action sur untangle.lol :",
  altruismLoadingMsg:"Tu fais quelque chose de merveilleux pour les autres.",
  altruisticSugg:["Je veux faire du bénévolat dans une banque alimentaire","Je veux devenir aidant·e pour un proche","Je veux créer un jardin partagé","Je veux donner mon sang régulièrement","Je veux encadrer un jeune en difficulté","Je veux organiser une collecte pour une association","Je veux aider les personnes âgées de mon quartier","Je veux m'occuper d'animaux dans un refuge","Je veux sensibiliser au changement climatique","Je veux aider des adultes à apprendre à lire"],
  phSugg:["Je veux mieux dormir","Je veux apprendre la guitare","Je veux faire du sport chaque jour","Je veux écrire un livre","Je veux manger plus sainement","Je veux apprendre une nouvelle langue","Je veux moins utiliser les réseaux sociaux","Je veux créer ma propre entreprise","Je veux passer plus de temps en famille","Je veux méditer chaque matin","Je veux rembourser mes dettes","Je veux courir un marathon","Je veux apprendre à cuisiner","Je veux trouver un nouvel emploi","Je veux épargner davantage"],
  woop:"Essayer WOOP",woopOr:"ou",woopTitle:"Méthode WOOP",
  woopSub:"Une technique éprouvée pour transformer les souhaits en actions — étape par étape.",
  woopLabels:["Souhait","Résultat","Obstacle","Plan"],
  woopHints:[
    "Que désires-tu vraiment ? Choisis quelque chose qui te tient à cœur — ambitieux mais réalisable.",
    "Imagine le meilleur résultat possible. Que ressens-tu quand ton souhait se réalise ?",
    "Quel est le principal obstacle intérieur — une habitude, un sentiment ou une pensée — qui pourrait te bloquer ?",
    "Si [obstacle], alors je vais [action]. Fais un plan si-alors concret.",
  ],
  woopPh:[
    "Ex. 'Je veux faire du sport chaque matin'",
    "Ex. 'Je me sens plein d'énergie et fier de moi'",
    "Ex. 'Je remets mon réveil à plus tard parce que je suis fatigué·e'",
    "Ex. 'Si je remets mon réveil, je prépare mes affaires de sport la veille au soir'",
  ],
  woopGo:"Créer mon plan →",woopLink:"En savoir plus sur la science",woopSummaryTitle:"Ton WOOP",
  suggLabel:"Pas sûr(e) quoi écrire ? Choisis une suggestion",
  recentQ:"Questions récentes",
  taClrConfirm:"effacer?",
  celebTitle:"Félicitations !",
  celebMsg:"Tu as complété toutes les étapes. Bravo — ça se fête !",
  celebBtn:"Merci !",
  fbTitle:"Feedback",fbPh:"Quelque chose ne va pas ou une suggestion ? Dites-nous…",fbSend:"Envoyer",fbCancel:"Annuler",fbSent:"Reçu, merci !",fbErr:"Échec — réessayez",fbHint:"⌘↵ pour envoyer",
  dyslexia:"Police adaptée à la dyslexie",
  payTitle:"Obtenir plus de questions",
  paySubtitle:"Chaque question génère un plan d'action IA complet",
  payLoginRequired:"Connectez-vous pour acheter des questions",
  payLoginDesc:"Créez un compte gratuit pour acheter des questions et les conserver sur tous vos appareils.",
  paySecure:"Paiement sécurisé via Stripe & Mollie",
  perQ:"/ question",
  tierStarter:"Débutant",
  tierPopular:"Populaire",
  tierPower:"Pro",
  tierCustom:"Personnalisé",
  tierCustomLabel:"Nombre de questions (min. 50)",
  tierBadge:"Le plus populaire",
  settingsTitle:"Compte & questions",
  topUp:"Acheter des questions",
  howToUse:"Comment ça marche",
  remaining:"restantes",
  fbPageDesc:"Quelque chose ne fonctionne pas, ou tu as une suggestion ? On lit chaque message et on utilise tes retours pour améliorer untangle.lol pour tout le monde.",
  dWName:"Bon retour, {name} !",
  pageTitle:"untangle.lol — Planificateur d'objectifs IA gratuit",
  madeBy:"Rendu possible par Bach Software",
};
export default fr;
