const fr = {
  code:"fr",label:"Français",flag:"🇫🇷",
  ph:"Ex. 'Mieux dormir' 🎸",
  hero:"Que veux-tu accomplir ?",
  heroS:["Tape-le.","Aucune question n'est trop bizarre.","Grand ou petit — tout est permis.","Qu'est-ce qui t'occupe l'esprit ?","Écris-le, on t'aide à avancer."],
  go:"Commençons →",back:"← Retour",out:"Déco",clr:"🗑️ Effacer",nG:"➕ Nouveau",noG:"Pas d'objectifs. On commence !",
  prog:"progrès",allD:"🎉 Fini !",sOf:"de",
  eth:"🌍 Conseils respectueux",
  err:"Oups !",resB:"← Retour",dW:"Re-bonjour",dS:"Tes objectifs.",
  byok:"Entrer la clé API",byokH1:"Utilise ta propre clé API",chAuth:"Changer auth",rmKey:"Supprimer clé",lSel:"Langue",
  byokL:"Clé API (Anthropic ou OpenRouter)",byokPh:"sk-ant-... ou sk-or-...",byokSave:"Enregistrer",
  byokNote:"Stockée dans ton navigateur. Jamais partagée.",
  apiKeyBadge:"🔑 Clé API",apiKeyUnset:"définir",checking:"Vérification...",chooseLang:"Choisis ta langue",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Accès direct à Claude. Les clés commencent par",
  byokAnthS1:"Aller sur console.anthropic.com",byokAnthS2:"S'inscrire / se connecter",byokAnthS3:"Paramètres → Clés API → Créer une clé",byokAnthLink:"Obtenir une clé Anthropic →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Pay-as-you-go. Souvent moins cher. Les clés commencent par",
  byokOrS1:"Aller sur openrouter.ai",byokOrS2:"S'inscrire / se connecter",byokOrS3:"Clés → Créer une clé",byokOrLink:"Obtenir une clé OpenRouter →",
  keyErrFmt:"La clé doit commencer par sk-ant- ou sk-or-",keyErrInv:"Clé invalide : ",keyErrNet:"API inaccessible — clé sauvegardée quand même.",
  usageStat:"Statistiques d'utilisation",apiCalls:"Appels API",estCost:"Coût estimé",inputTok:"Tokens en entrée",outputTok:"Tokens en sortie",resetStats:"Réinitialiser",
  rmTip:"Supprimer",start:"Démarrer",cred:"crédits",credFree:"crédits gratuits",credOut:"Plus de crédits",
  credOutMsg:"Tes crédits gratuits sont épuisés. Ajoute ta propre clé API pour continuer — gratuite chez Anthropic ou OpenRouter.",
  credByok:"Ajouter ma clé →",
  lp:["🧠 Réflexion...","☕ Brassage d'idées...","🔮 Boule de cristal en chauffe...","🧙 Sorts en cours...","🤔 Pensée profonde...","🎯 Concentration..."],
  topUp:"Recharger les crédits",topUpDesc:"10 crédits pour €2,50",topUpBtn:"Payer avec Stripe →",
  topUpSuccess:"Paiement réussi ! Les crédits seront ajoutés sous peu.",topUpPending:"Traitement des crédits...",
  topUpPopupTitle:"Crédits ajoutés ! 🎉",
  topUpPopupMsg:"untangle.lol est gratuit et privé — sans pub ni collecte de données. Les crédits font tourner l'IA et soutiennent un produit équitable et indépendant. Merci !",
  topUpPopupBtn:"Super, c'est parti !",
  altruismPopupTitle:"Comme c'est gentil ! 💛",
  altruismPopupMsg:"Ton objectif consiste à aider les autres — bénévolat, aidant·e ou soutien à une bonne cause. Cela mérite une récompense : complète toutes les étapes et gagne automatiquement 10 crédits gratuits !",
  altruismPopupBtn:"Super, c'est parti !",
  altruismBonusTitle:"🎁 +10 crédits gagnés !",
  altruismBonusMsg:"Félicitations ! Tu as accompli ton objectif altruiste. En remerciement de ton engagement envers les autres, nous avons ajouté 10 crédits gratuits à ton compte.",
  altruismBonusBtn:"Super, merci !",
  altruismTeaser:"💛 Tu veux aider les autres ? Entre un objectif altruiste et gagne 10 crédits gratuits en le complétant.",
  altruismPopupMsgRepeat:"Ton objectif consiste à aider les autres — c'est vraiment magnifique. Complète toutes les étapes et fais une vraie différence !",
  analyticsNote:"Nous collectons des statistiques d'utilisation anonymes (sans cookies ni données personnelles).",
  signIn:"Se connecter avec Google",signInSub:"Sauvegarde tes objectifs sur tous tes appareils",signOut:"Déconnexion",
  profile:"Profil",terms:"CGU",privacy:"Confidentialité",stats:"Statistiques",donate:"❤️ Faire un don",revenue:"Revenus",revTotal:"Total des revenus",revEmpty:"Aucune transaction pour l'instant.",revMore:"Charger plus",
  share:"Partager",shareCopy:"Copier",shareCopied:"Copié !",shareMsg:"Découvre mon plan d'action sur untangle.lol :",
  altruismLoadingMsg:"💛 Tu fais quelque chose de merveilleux pour les autres.",
  altruisticSugg:["Je veux faire du bénévolat dans une banque alimentaire","Je veux devenir aidant·e pour un proche","Je veux créer un jardin partagé","Je veux donner mon sang régulièrement","Je veux encadrer un jeune en difficulté"],
  phSugg:["Je veux mieux dormir","Je veux apprendre la guitare","Je veux faire du sport chaque jour","Je veux écrire un livre","Je veux manger plus sainement"],
  woop:"🎯 Essayer WOOP",woopOr:"ou",woopTitle:"Méthode WOOP",
  woopSub:"Une technique éprouvée pour transformer les souhaits en actions — étape par étape.",
  woopLabels:["Souhait","Résultat","Obstacle","Plan"],
  woopHints:[
    "Que désires-tu vraiment ? Choisis quelque chose qui te tient à cœur — ambitieux mais réalisable.",
    "Imagine le meilleur résultat possible. Que ressens-tu quand ton souhait se réalise ?",
    "Quel est le principal obstacle intérieur — une habitude, un sentiment ou une pensée — qui pourrait te bloquer ?",
    "Si [obstacle], alors je vais [action]. Fais un plan si-alors concret.",
  ],
  woopPh:[
    "Ex. 'Je veux faire du sport chaque matin'",
    "Ex. 'Je me sens plein d'énergie et fier de moi'",
    "Ex. 'Je remets mon réveil à plus tard parce que je suis fatigué·e'",
    "Ex. 'Si je remets mon réveil, je prépare mes affaires de sport la veille au soir'",
  ],
  woopGo:"Créer mon plan →",woopLink:"En savoir plus sur la science",woopSummaryTitle:"Ton WOOP",
  suggLabel:"💡 Choisir une suggestion",
  taClrConfirm:"effacer?",
  celebTitle:"Félicitations ! 🎉",
  celebMsg:"Tu as complété toutes les étapes. Bravo — ça se fête !",
  celebBtn:"Merci !",
};
export default fr;
