const id = {
  code:"id",label:"Bahasa Indonesia",flag:"🇮🇩",
  ph:"Mis. 'Saya ingin tidur lebih baik' atau 'Saya ingin belajar gitar' 🎸",
  hero:"Apa yang ingin Anda capai?",
  heroS:["Cukup ketik saja.","Tidak ada pertanyaan yang aneh.","Besar atau kecil — semua boleh.","Apa yang ada di pikiranmu?","Tulis saja, kami bantu kamu melangkah maju."],
  go:"Ayo mulai →",back:"← Kembali",out:"Keluar",clr:"🗑️ Hapus semua",nG:"➕ Tujuan baru",noG:"Belum ada tujuan. Saatnya mulai!",
  prog:"kemajuan",allD:"🎉 Semua selesai!",sOf:"dari",
  eth:"🌍 Saran dengan hormat untuk manusia, planet, dan kesejahteraan",
  err:"Ups, coba lagi!",resB:"← Kembali ke ringkasan",dW:"Selamat datang kembali",dS:"Ini tujuan-tujuanmu.",
  byok:"Masukkan kunci API",byokH1:"Gunakan kunci API sendiri",chAuth:"Ganti autentikasi",rmKey:"Hapus kunci",lSel:"Bahasa",
  byokL:"Kunci API (Anthropic atau OpenRouter)",byokPh:"sk-ant-... atau sk-or-...",byokSave:"Simpan & lanjutkan",
  byokNote:"Tersimpan di browser Anda saja. Tidak pernah dibagikan.",
  apiKeyBadge:"🔑 Kunci API",apiKeyUnset:"atur",checking:"Memeriksa...",chooseLang:"Pilih bahasa Anda",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Akses langsung ke Claude. Kunci dimulai dengan",
  byokAnthS1:"Buka console.anthropic.com",byokAnthS2:"Daftar / masuk",byokAnthS3:"Pengaturan → Kunci API → Buat kunci",byokAnthLink:"Dapatkan kunci Anthropic →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Bayar sesuai penggunaan. Seringkali lebih murah. Kunci dimulai dengan",
  byokOrS1:"Buka openrouter.ai",byokOrS2:"Daftar / masuk",byokOrS3:"Kunci → Buat kunci",byokOrLink:"Dapatkan kunci OpenRouter →",
  keyErrFmt:"Kunci harus dimulai dengan sk-ant- atau sk-or-",keyErrInv:"Kunci tidak valid: ",keyErrNet:"Tidak dapat memverifikasi dengan API — kunci tetap tersimpan.",
  usageStat:"Statistik penggunaan",apiCalls:"Panggilan API",estCost:"Perkiraan biaya",inputTok:"Token masukan",outputTok:"Token keluaran",resetStats:"Reset statistik",
  rmTip:"Hapus",start:"Mulai",cred:"kredit",credFree:"kredit gratis",credOut:"Kredit habis",
  credOutMsg:"Kredit gratis Anda habis. Tambahkan kunci API sendiri untuk melanjutkan — gratis dari Anthropic atau OpenRouter.",
  credByok:"Tambah kunci sendiri →",
  lp:["🧠 Berpikir...","☕ Menyeduh ide...","🔮 Bola kristal memanas...","🧙 Menjalankan sihir...","🤔 Berpikir mendalam...","🎯 Mengunci tujuan..."],
  topUp:"Isi ulang kredit",topUpDesc:"10 kredit seharga €1,00",topUpBtn:"Bayar dengan Stripe →",
  topUpSuccess:"Pembayaran berhasil! Kredit akan segera ditambahkan.",topUpPending:"Memproses kredit...",
  topUpPopupTitle:"Kredit ditambahkan! 🎉",
  topUpPopupMsg:"untangle.lol gratis dan privat — tanpa iklan, tanpa pengumpulan data. Kredit membuat AI tetap berjalan dan mendukung produk yang adil dan independen. Terima kasih!",
  topUpPopupBtn:"Bagus, ayo mulai!",
  altruismPopupTitle:"Betapa baiknya kamu! 💛",
  altruismPopupMsg:"Tujuanmu tentang membantu orang lain — seperti menjadi sukarelawan, merawat, atau mendukung tujuan mulia. Ini layak mendapat hadiah: selesaikan semua langkah dan dapatkan 10 kredit gratis secara otomatis!",
  altruismPopupBtn:"Bagus, ayo mulai!",
  altruismBonusTitle:"🎁 +10 kredit diperoleh!",
  altruismBonusMsg:"Selamat! Kamu menyelesaikan tujuan altruistikmu. Sebagai ucapan terima kasih atas usahamu membantu orang lain, kami telah menambahkan 10 kredit gratis ke akunmu.",
  altruismBonusBtn:"Luar biasa, terima kasih!",
  altruismTeaser:"💛 Ingin membantu orang lain? Masukkan tujuan altruistik dan dapatkan 10 kredit gratis saat menyelesaikannya.",
  altruismPopupMsgRepeat:"Tujuanmu tentang membantu orang lain — sungguh luar biasa. Selesaikan semua langkah dan buat perbedaan nyata!",
  analyticsNote:"Kami mengumpulkan statistik penggunaan anonim (tanpa cookie, tanpa data pribadi).",
  signIn:"Masuk dengan Google",signInSub:"Simpan tujuanmu di semua perangkat",signOut:"Keluar",
  profile:"Profil",terms:"Ketentuan",privacy:"Privasi",stats:"Statistik",donate:"❤️ Donasi",revenue:"Pendapatan",
  share:"Bagikan",shareCopy:"Salin",shareCopied:"Tersalin!",shareMsg:"Lihat rencana aksi saya di untangle.lol:",
  altruismLoadingMsg:"💛 Kamu sedang melakukan sesuatu yang luar biasa untuk orang lain.",
  altruisticSugg:["Saya ingin menjadi sukarelawan di bank makanan","Saya ingin menjadi pengasuh anggota keluarga","Saya ingin menjadi mentor bagi pemuda","Saya ingin rutin mendonorkan darah","Saya ingin memulai taman komunitas"],
  phSugg:["Saya ingin tidur lebih baik","Saya ingin belajar gitar","Saya ingin berolahraga setiap hari","Saya ingin menulis buku","Saya ingin makan lebih sehat"],
  woop:"🎯 Coba WOOP",woopOr:"atau",woopTitle:"Metode WOOP",
  woopSub:"Teknik terbukti untuk mengubah keinginan menjadi tindakan — langkah demi langkah.",
  woopLabels:["Keinginan","Hasil","Hambatan","Rencana"],
  woopHints:[
    "Apa yang benar-benar kamu inginkan? Pilih sesuatu yang menyentuh hatimu — menantang tapi bisa dicapai.",
    "Bayangkan hasil terbaik yang mungkin. Bagaimana rasanya saat keinginanmu terkabul?",
    "Apa hambatan batin utama — kebiasaan, perasaan, atau pikiran — yang bisa menghalangimu?",
    "Jika [hambatan], maka saya akan [tindakan]. Buat rencana jika-maka yang spesifik.",
  ],
  woopPh:[
    "Mis. 'Saya ingin berolahraga setiap pagi'",
    "Mis. 'Saya merasa bersemangat dan bangga pada diri sendiri'",
    "Mis. 'Saya mematikan alarm karena ngantuk'",
    "Mis. 'Jika saya mematikan alarm, saya akan menyiapkan pakaian olahraga malam sebelumnya'",
  ],
  woopGo:"Buat rencanaku →",woopLink:"Pelajari tentang ilmunya",woopSummaryTitle:"WOOP-mu",
  suggLabel:"💡 Pilih saran",
  taClrConfirm:"hapus?",
  celebTitle:"Selamat! 🎉",
  celebMsg:"Kamu telah menyelesaikan semua langkah. Bagus sekali — ini layak dirayakan!",
  celebBtn:"Terima kasih!",
};
export default id;
