const ja = {
  code:"ja",label:"日本語",flag:"🇯🇵",
  ph:"例：「もっとよく眠りたい」または「ギターを習いたい」🎸",
  hero:"何を達成したいですか？",
  heroS:["入力するだけ。","どんな質問でもOK。","大きくても小さくても — 何でも構いません。","何を考えていますか？","書いてみてください、一緒に解決しましょう。"],
  go:"始めましょう →",back:"← 戻る",out:"ログアウト",clr:"🗑️ すべて削除",nG:"➕ 新しい目標",noG:"まだ目標がありません。始めましょう！",
  prog:"進捗",allD:"🎉 すべて完了！",sOf:"/",
  eth:"🌍 人・地球・健康に配慮したアドバイス",
  err:"エラーが発生しました、もう一度お試しください！",resB:"← 概要に戻る",dW:"おかえりなさい",dS:"あなたの目標一覧です。",
  byok:"APIキーを入力",byokH1:"自分のAPIキーを使う",chAuth:"認証を変更",rmKey:"キーを削除",lSel:"言語",
  byokL:"APIキー（AnthropicまたはOpenRouter）",byokPh:"sk-ant-... または sk-or-...",byokSave:"保存して続ける",
  byokNote:"ブラウザにのみ保存されます。共有されることはありません。",
  apiKeyBadge:"🔑 APIキー",apiKeyUnset:"設定する",checking:"確認中...",chooseLang:"言語を選んでください",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Claudeへの直接アクセス。キーは",
  byokAnthS1:"console.anthropic.comにアクセス",byokAnthS2:"サインアップ / ログイン",byokAnthS3:"設定 → APIキー → キーを作成",byokAnthLink:"Anthropicキーを取得 →",
  byokOrTitle:"OpenRouter",byokOrDesc:"従量課金制。多くの場合より安い。キーは",
  byokOrS1:"openrouter.aiにアクセス",byokOrS2:"サインアップ / ログイン",byokOrS3:"キー → キーを作成",byokOrLink:"OpenRouterキーを取得 →",
  keyErrFmt:"キーはsk-ant-またはsk-or-で始まる必要があります",keyErrInv:"無効なキー：",keyErrNet:"APIで確認できませんでした — キーは保存されました。",
  usageStat:"使用統計",apiCalls:"API呼び出し",estCost:"概算コスト",inputTok:"入力トークン",outputTok:"出力トークン",resetStats:"統計をリセット",
  rmTip:"削除",start:"開始",cred:"クレジット",credFree:"無料クレジット",credOut:"クレジット不足",
  credOutMsg:"無料クレジットがなくなりました。続けるには自分のAPIキーを追加してください — AnthropicまたはOpenRouterから無料で取得できます。",
  credByok:"自分のキーを追加 →",
  lp:["🧠 考え中...","☕ アイデアを醸造中...","🔮 水晶球が温まっています...","🧙 魔法をかけています...","🤔 深く考えています...","🎯 目標に集中中..."],
  topUp:"クレジットを追加",topUpDesc:"10クレジットで€1.00",topUpBtn:"Stripeで支払う →",
  topUpSuccess:"支払い完了！クレジットはまもなく追加されます。",topUpPending:"クレジットを処理中...",
  topUpPopupTitle:"クレジットが追加されました！ 🎉",
  topUpPopupMsg:"untangle.lolは無料でプライベートです — 広告なし、データ収集なし。クレジットでAIを動かし続け、公正で独立したプロダクトを支えています。ご支援ありがとうございます！",
  topUpPopupBtn:"ありがとう、始めましょう！",
  altruismPopupTitle:"なんて親切なんでしょう！ 💛",
  altruismPopupMsg:"あなたの目標は他者を助けること — ボランティア、介護、または良い活動への支援など。それは報酬に値します：すべてのステップを完了すると、自動的に10クレジットを獲得できます！",
  altruismPopupBtn:"ありがとう、始めましょう！",
  altruismBonusTitle:"🎁 +10クレジット獲得！",
  altruismBonusMsg:"おめでとうございます！利他的な目標を達成しました。他者への貢献に感謝して、アカウントに10の無料クレジットを追加しました。",
  altruismBonusBtn:"素晴らしい、ありがとう！",
  altruismTeaser:"💛 他者を助けたいですか？利他的な目標を入力してすべてのステップを完了すると、10の無料クレジットを獲得できます。",
  altruismPopupMsgRepeat:"あなたの目標は他者を助けること — それは本当に素晴らしいです。すべてのステップを完了して、本当の違いを生み出しましょう！",
  analyticsNote:"匿名の使用統計を収集しています（Cookieなし、個人データなし）。",
  signIn:"Googleでサインイン",signInSub:"すべてのデバイスで目標を保存",signOut:"サインアウト",
  profile:"プロフィール",terms:"利用規約",privacy:"プライバシー",stats:"統計",donate:"❤️ 寄付",
  share:"シェア",shareCopy:"コピー",shareCopied:"コピーしました！",shareMsg:"untangle.lolで私のアクションプランを見てください：",
  altruismLoadingMsg:"💛 あなたは他者のために素晴らしいことをしています。",
  altruisticSugg:["フードバンクでボランティアしたい","家族の介護をしたい","若者のメンターになりたい","定期的に献血したい","コミュニティガーデンを始めたい"],
  phSugg:["もっとよく眠りたい","ギターを習いたい","毎日運動したい","本を書きたい","もっと健康的に食べたい"],
  woop:"🎯 WOOPを試す",woopOr:"または",woopTitle:"WOOP法",
  woopSub:"願いを行動に変える実証済みの技術 — 一歩ずつ。",
  woopLabels:["願い","結果","障害","計画"],
  woopHints:[
    "本当に何が欲しいですか？心に触れるものを選んでください — 挑戦的でも達成可能なもの。",
    "最良の結果を想像してください。願いが叶ったとき、どんな気持ちになりますか？",
    "あなたを妨げる可能性のある主な内部障害は何ですか — 習慣、感情、または思考？",
    "もし[障害]なら、[行動]します。具体的なif-thenプランを作ってください。",
  ],
  woopPh:[
    "例：「毎朝運動したい」",
    "例：「エネルギッシュで自分を誇りに思う」",
    "例：「疲れているのでアラームを止めてしまう」",
    "例：「アラームを止めたら、前夜にジムの服を用意する」",
  ],
  woopGo:"プランを作成 →",woopLink:"科学について学ぶ",woopSummaryTitle:"あなたのWOOP",
  suggLabel:"💡 提案を選ぶ",
  taClrConfirm:"クリアしますか？",
  celebTitle:"おめでとうございます！ 🎉",
  celebMsg:"すべてのステップを完了しました。よくできました — これはお祝いに値します！",
  celebBtn:"ありがとう！",
};
export default ja;
