const nl = {
  code:"nl",label:"Nederlands",flag:"🇳🇱",
  ph:"Begin met typen...",
  hero:"Wat wil je bereiken?",heroLabel:"Stel hier de vraag die je bezig houdt",
  heroS:["Typ het maar in.","Geen vraag is te gek.","Klein of groot — alles mag.","Wat houdt je bezig?","Schrijf het op, wij helpen verder."],
  go:"Laten we beginnen →",back:"← Terug",out:"Uitloggen",clr:"🗑️ Alles wissen",nG:"➕ Nieuw doel",noG:"Nog geen doelen. Tijd om te beginnen!",
  prog:"voortgang",allD:"🎉 Alles afgerond!",sOf:"van",
  eth:"🌍 Advies met respect voor mens, planeet en welzijn",
  err:"Oeps, probeer het nog eens!",resB:"← Terug naar overzicht",dW:"Welkom terug",dS:"Hier zijn je doelen.",
  byok:"Voer je API-sleutel in",byokH1:"Breng je eigen API-sleutel mee",chAuth:"Authenticatie wijzigen",rmKey:"Sleutel verwijderen",lSel:"Taal",
  byokL:"API-sleutel (Anthropic of OpenRouter)",byokPh:"sk-ant-... of sk-or-...",byokSave:"Opslaan & beginnen",
  byokNote:"Opgeslagen in je browser. Nooit gedeeld.",
  apiKeyBadge:"🔑 API-sleutel",apiKeyUnset:"instellen",checking:"Controleren...",chooseLang:"Kies je taal",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Directe toegang tot Claude. Sleutels beginnen met",
  byokAnthS1:"Ga naar console.anthropic.com",byokAnthS2:"Aanmelden / inloggen",byokAnthS3:"Instellingen → API-sleutels → Sleutel aanmaken",byokAnthLink:"Haal Anthropic-sleutel op →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Betaal per gebruik. Vaak goedkoper. Sleutels beginnen met",
  byokOrS1:"Ga naar openrouter.ai",byokOrS2:"Aanmelden / inloggen",byokOrS3:"Sleutels → Sleutel aanmaken",byokOrLink:"Haal OpenRouter-sleutel op →",
  keyErrFmt:"Sleutel moet beginnen met sk-ant- of sk-or-",keyErrInv:"Ongeldige sleutel: ",keyErrNet:"API niet bereikbaar — sleutel toch opgeslagen.",
  usageStat:"Gebruiksstatistieken",apiCalls:"API-aanroepen",estCost:"Geschatte kosten",inputTok:"Invoertokens",outputTok:"Uitvoertokens",resetStats:"Statistieken wissen",
  rmTip:"Verwijderen",start:"Start",cred:"credits",credFree:"gratis credits",credOut:"Geen credits meer",
  credOutMsg:"Je gratis credits zijn op. Voeg je eigen API-sleutel toe om door te gaan — gratis bij Anthropic en OpenRouter.",
  credByok:"Eigen sleutel toevoegen →",
  lp:["🧠 Nadenken...","☕ Ideeën brouwen...","🔮 Kristallen bol opwarmen...","🧙 Spreuken uitspreken...","🤔 Diep nadenken...","🎯 Scherp stellen..."],
  topUp:"Credits bijkopen",topUpDesc:"10 credits voor €2,50",topUpBtn:"Betalen met Stripe →",
  topUpSuccess:"Betaling geslaagd! Credits worden bijgeschreven.",topUpPending:"Credits worden verwerkt...",
  topUpPopupTitle:"Credits bijgeschreven! 🎉",
  topUpPopupMsg:"untangle.lol is gratis en privé — zonder advertenties of dataverzameling. Met credits houd je de AI aan het draaien en steun je een eerlijk, onafhankelijk product. Dank je wel!",
  topUpPopupBtn:"Top, laten we beginnen!",
  altruismPopupTitle:"Wat lief van je! 💛",
  altruismPopupMsg:"Je doel gaat over het helpen van anderen — zoals vrijwilligerswerk, mantelzorg of een goed doel. Dat verdient een beloning: rond álle stappen af en ontvang automatisch 3 gratis credits!",
  altruismPopupBtn:"Top, ik ga aan de slag!",
  altruismBonusTitle:"🎁 +3 credits verdiend!",
  altruismBonusMsg:"Gefeliciteerd! Je hebt je altruïstische doel afgerond. Als dank voor je inzet voor anderen hebben we 3 gratis credits aan je account toegevoegd.",
  altruismBonusBtn:"Super, bedankt!",
  altruismTeaser:"💛 Als je iets doet voor een ander verdien je 3 gratis credits.",
  altruismPopupMsgRepeat:"Je doel gaat over het helpen van anderen — wat ontzettend mooi is. Rond álle stappen af en maak echt het verschil!",
  analyticsNote:"We verzamelen anonieme gebruiksstatistieken (geen cookies, geen persoonsgegevens).",
  signIn:"Inloggen met Google",signInSub:"Sla je doelen op via al je apparaten",signOut:"Uitloggen",
  profile:"Profiel",terms:"Voorwaarden",privacy:"Privacy",stats:"Statistieken",donate:"❤️ Doneer",donateMsg:"❤️ Jouw donatie draagt bij aan een betere wereld",revenue:"Omzet",revTotal:"Totale omzet",revEmpty:"Nog geen transacties.",revMore:"Meer laden",
  share:"Delen",shareCopy:"Kopiëren",shareCopied:"Gekopieerd!",shareMsg:"Bekijk mijn stappenplan op untangle.lol:",
  altruismLoadingMsg:"💛 Je bent iets moois aan het doen voor anderen.",
  altruisticSugg:["Ik wil vrijwilligerswerk doen bij een voedselbank","Ik wil mantelzorger worden voor een familielid","Ik wil een buurtmoestuin starten","Ik wil bloed doneren","Ik wil een mentorrol op me nemen voor een jongere","Ik wil een inzamelingsactie organiseren voor een goed doel","Ik wil ouderen in mijn buurt helpen","Ik wil dieren helpen in een dierenopvang","Ik wil een bewustwordingscampagne starten over klimaat","Ik wil mensen helpen bij het leren lezen"],
  phSugg:["Ik wil beter slapen","Ik wil leren gitaarspelen","Ik wil elke dag sporten","Ik wil een boek schrijven","Ik wil gezonder eten","Ik wil een nieuwe taal leren","Ik wil minder op social media zitten","Ik wil mijn eigen bedrijf starten","Ik wil meer tijd doorbrengen met mijn gezin","Ik wil elke ochtend mediteren","Ik wil mijn schulden aflossen","Ik wil een marathon lopen","Ik wil leren koken","Ik wil een nieuwe baan vinden","Ik wil meer spaargeld opbouwen"],
  woop:"🎯 Probeer WOOP",woopOr:"of",woopTitle:"WOOP-methode",
  woopSub:"Een bewezen techniek om doelen om te zetten in actie — stap voor stap.",
  woopLabels:["Wens","Uitkomst","Obstakel","Plan"],
  woopHints:[
    "Wat wil je echt bereiken? Kies iets wat je raakt — uitdagend maar haalbaar.",
    "Stel je het beste resultaat voor. Hoe voel je je als je wens uitkomt?",
    "Wat is het grootste interne obstakel — een gewoonte, gevoel of gedachte — dat je kan tegenhouden?",
    "Als [obstakel], dan zal ik [actie]. Maak een concreet als-dan-plan.",
  ],
  woopPh:[
    "Bijv. 'Ik wil elke ochtend sporten'",
    "Bijv. 'Ik voel me energiek en trots op mezelf'",
    "Bijv. 'Ik sla de wekker af omdat ik moe ben'",
    "Bijv. 'Als ik de wekker afzet, leg ik mijn sportkleren klaar de avond ervoor'",
  ],
  woopGo:"Maak mijn plan →",woopLink:"Meer over de wetenschap",woopSummaryTitle:"Jouw WOOP",
  suggLabel:"💡 Kies een suggestie",
  taClrConfirm:"wis?",
  celebTitle:"Gefeliciteerd! 🎉",
  celebMsg:"Je hebt alle stappen afgerond. Goed gedaan — dit verdient een feestje!",
  celebBtn:"Bedankt!",
  fbTitle:"Feedback",fbPh:"Iets kapot of een suggestie? Laat het ons weten…",fbSend:"Verstuur",fbCancel:"Annuleer",fbSent:"Ontvangen, bedankt!",fbErr:"Mislukt — probeer opnieuw",fbHint:"⌘↵ versturen",
  dyslexia:"Dyslexievriendelijk lettertype",
  braille:"Braille-lettertype",
};
export default nl;
