const nl = {
  code:"nl",label:"Nederlands",flag:"🇳🇱",
  ph:"Begin met typen...",
  hero:"Wat wil je bereiken?",heroLabel:"Stel hier de vraag die je bezig houdt",
  heroS:["Typ het maar in.","Geen vraag is te gek.","Klein of groot — alles mag.","Wat houdt je bezig?","Schrijf het op, wij helpen verder."],
  go:"Laten we beginnen →",back:"Terug",out:"Uitloggen",clr:"Alles wissen",nG:"Nieuw doel",noG:"Nog geen doelen. Tijd om te beginnen!",
  prog:"voortgang",allD:"Alles afgerond!",sOf:"van",
  eth:"Advies met respect voor mens, planeet en welzijn",
  err:"Oeps, probeer het nog eens!",resB:"← Terug naar overzicht",dW:"Welkom terug",dS:"Hier zijn je doelen.",
  byok:"Voer je API-sleutel in",byokH1:"Breng je eigen API-sleutel mee",chAuth:"Authenticatie wijzigen",rmKey:"Sleutel verwijderen",lSel:"Taal",
  byokL:"API-sleutel (Anthropic of OpenRouter)",byokPh:"sk-ant-... of sk-or-...",byokSave:"Opslaan & beginnen",
  byokNote:"Opgeslagen in je browser. Nooit gedeeld.",
  apiKeyBadge:"API-sleutel",apiKeyUnset:"instellen",checking:"Controleren...",chooseLang:"Kies je taal",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Directe toegang tot Claude. Sleutels beginnen met",
  byokAnthS1:"Ga naar console.anthropic.com",byokAnthS2:"Aanmelden / inloggen",byokAnthS3:"Instellingen → API-sleutels → Sleutel aanmaken",byokAnthLink:"Haal Anthropic-sleutel op →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Betaal per gebruik. Vaak goedkoper. Sleutels beginnen met",
  byokOrS1:"Ga naar openrouter.ai",byokOrS2:"Aanmelden / inloggen",byokOrS3:"Sleutels → Sleutel aanmaken",byokOrLink:"Haal OpenRouter-sleutel op →",
  keyErrFmt:"Sleutel moet beginnen met sk-ant- of sk-or-",keyErrInv:"Ongeldige sleutel: ",keyErrNet:"API niet bereikbaar — sleutel toch opgeslagen.",
  usageStat:"Gebruiksstatistieken",apiCalls:"API-aanroepen",estCost:"Geschatte kosten",inputTok:"Invoertokens",outputTok:"Uitvoertokens",resetStats:"Statistieken wissen",
  rmTip:"Verwijderen",start:"Start",cred:"vragen",credFree:"gratis vragen",credOut:"Geen vragen meer",
  credOutMsg:"Je gratis vragen zijn op. Voeg je eigen API-sleutel toe om door te gaan — gratis bij Anthropic en OpenRouter.",
  credByok:"Eigen sleutel toevoegen →",
  lp:["Nadenken...","Ideeën brouwen...","Kristallen bol opwarmen...","Spreuken uitspreken...","Diep nadenken...","Scherp stellen..."],
  topUpDesc:"10 vragen voor €2,50",topUpBtn:"Betalen met Stripe →",
  topUpSuccess:"Betaling geslaagd! Vragen worden bijgeschreven.",topUpPending:"Vragen worden verwerkt...",
  topUpPopupTitle:"Vragen bijgeschreven!",
  topUpPopupMsg:"untangle.lol is gratis en privé — zonder advertenties of dataverzameling. Met vragen houd je de AI aan het draaien en steun je een eerlijk, onafhankelijk product. Dank je wel!",
  topUpPopupBtn:"Top, laten we beginnen!",
  altruismPopupTitle:"Wat lief van je!",
  altruismPopupMsg:"Je doel is voor een ander — deel je stappenplan en ontvang 2 gratis vragen.",
  altruismPopupBtn:"Plan delen →",
  altruismBonusTitle:"+2 vragen verdiend!",
  altruismBonusMsg:"Je hebt je plan gedeeld! Als dank ontvang je 2 gratis vragen.",
  altruismBonusBtn:"Super, bedankt!",
  altruismTeaser:"Goed bezig! Deel je plan met de ander en ontvang 2 gratis vragen.",
  altruismPopupMsgRepeat:"Je doel helpt anderen — mooi! Deel je plan en inspireer iemand.",
  altruismShareCta:"Deel dit plan en ontvang +2 gratis vragen",
  analyticsNote:"We verzamelen anonieme gebruiksstatistieken (geen cookies, geen persoonsgegevens).",
  signIn:"Inloggen met Google",signInSub:"Sla je doelen op via al je apparaten",signOut:"Uitloggen",
  profile:"Profiel",terms:"Voorwaarden",privacy:"Privacy",stats:"Statistieken",donate:"Doneer",donateMsg:"Jouw donatie draagt bij aan een betere wereld",revenue:"Omzet",revTotal:"Totale omzet",revEmpty:"Nog geen transacties.",revMore:"Meer laden",
  share:"Delen",shareCopy:"Kopiëren",shareCopied:"Gekopieerd!",shareMsg:"Bekijk mijn stappenplan op untangle.lol:",
  altruismLoadingMsg:"Je bent iets moois aan het doen voor anderen.",
  altruisticSugg:["Ik wil vrijwilligerswerk doen bij een voedselbank","Ik wil mantelzorger worden voor een familielid","Ik wil een buurtmoestuin starten","Ik wil bloed doneren","Ik wil een mentorrol op me nemen voor een jongere","Ik wil een inzamelingsactie organiseren voor een goed doel","Ik wil ouderen in mijn buurt helpen","Ik wil dieren helpen in een dierenopvang","Ik wil een bewustwordingscampagne starten over klimaat","Ik wil mensen helpen bij het leren lezen"],
  phSugg:["Ik wil beter slapen","Ik wil leren gitaarspelen","Ik wil elke dag sporten","Ik wil een boek schrijven","Ik wil gezonder eten","Ik wil een nieuwe taal leren","Ik wil minder op social media zitten","Ik wil mijn eigen bedrijf starten","Ik wil meer tijd doorbrengen met mijn gezin","Ik wil elke ochtend mediteren","Ik wil mijn schulden aflossen","Ik wil een marathon lopen","Ik wil leren koken","Ik wil een nieuwe baan vinden","Ik wil meer spaargeld opbouwen"],
  woop:"Probeer WOOP",woopOr:"of",woopTitle:"WOOP-methode",
  woopSub:"Een bewezen techniek om doelen om te zetten in actie — stap voor stap.",
  woopLabels:["Wens","Uitkomst","Obstakel","Plan"],
  woopHints:[
    "Wat wil je echt bereiken? Kies iets wat je raakt — uitdagend maar haalbaar.",
    "Stel je het beste resultaat voor. Hoe voel je je als je wens uitkomt?",
    "Wat is het grootste interne obstakel — een gewoonte, gevoel of gedachte — dat je kan tegenhouden?",
    "Als [obstakel], dan zal ik [actie]. Maak een concreet als-dan-plan.",
  ],
  woopPh:[
    "Bijv. 'Ik wil elke ochtend sporten'",
    "Bijv. 'Ik voel me energiek en trots op mezelf'",
    "Bijv. 'Ik sla de wekker af omdat ik moe ben'",
    "Bijv. 'Als ik de wekker afzet, leg ik mijn sportkleren klaar de avond ervoor'",
  ],
  woopGo:"Maak mijn plan →",woopLink:"Meer over de wetenschap",woopSummaryTitle:"Jouw WOOP",
  suggLabel:"Kom je er niet uit? Kies een suggestie hieronder",
  recentQ:"Recente vragen",
  taClrConfirm:"wis?",
  celebTitle:"Gefeliciteerd!",
  celebMsg:"Je hebt alle stappen afgerond. Goed gedaan — dit verdient een feestje!",
  celebBtn:"Bedankt!",
  fbTitle:"Feedback",fbPh:"Iets kapot of een suggestie? Laat het ons weten…",fbSend:"Verstuur",fbCancel:"Annuleer",fbSent:"Ontvangen, bedankt!",fbErr:"Mislukt — probeer opnieuw",fbHint:"⌘↵ versturen",
  dyslexia:"Dyslexievriendelijk lettertype",
  payTitle:"Meer vragen kopen",
  paySubtitle:"Elke vraag genereert een volledig AI-actieplan",
  payLoginRequired:"Log in om vragen te kopen",
  payLoginDesc:"Maak een gratis account aan om vragen te kopen en ze op al je apparaten te bewaren.",
  paySecure:"Veilig betalen via Stripe & Mollie",
  perQ:"/ vraag",
  tierStarter:"Starter",
  tierPopular:"Populair",
  tierPower:"Kracht",
  tierCustom:"Aangepast",
  tierCustomLabel:"Aantal vragen (min. 50)",
  tierBadge:"Meest gekozen",
  settingsTitle:"Account & vragen",
  topUp:"Vragen kopen",
  howToUse:"Uitleg",
  remaining:"resterend",
  fbPageDesc:"Iets werkt niet, of heb je een suggestie? We lezen elk bericht en gebruiken jouw feedback om untangle.lol beter te maken voor iedereen.",
  dWName:"Welkom terug, {name}!",
  madeBy:"Mogelijk gemaakt door Bach Software",
};
export default nl;
