const pt = {
  code:"pt",label:"Português",flag:"🇧🇷",
  ph:"Ex.: 'Quero dormir melhor' ou 'Quero aprender guitarra' 🎸",
  hero:"O que você quer alcançar?",
  heroS:["É só digitar.","Nenhuma pergunta é estranha demais.","Grande ou pequeno — tudo vale.","O que está na sua cabeça?","Escreva, nós ajudamos você a avançar."],
  go:"Vamos começar →",back:"← Voltar",out:"Sair",clr:"🗑️ Limpar tudo",nG:"➕ Nova meta",noG:"Nenhuma meta ainda. Hora de começar!",
  prog:"progresso",allD:"🎉 Tudo concluído!",sOf:"de",
  eth:"🌍 Conselhos com respeito pelas pessoas, planeta e bem-estar",
  err:"Ops, tente novamente!",resB:"← Voltar à visão geral",dW:"Bem-vindo de volta",dS:"Aqui estão suas metas.",
  byok:"Inserir chave de API",byokH1:"Use sua própria chave de API",chAuth:"Alterar autenticação",rmKey:"Remover chave",lSel:"Idioma",
  byokL:"Chave de API (Anthropic ou OpenRouter)",byokPh:"sk-ant-... ou sk-or-...",byokSave:"Salvar e continuar",
  byokNote:"Armazenada apenas no seu navegador. Nunca compartilhada.",
  apiKeyBadge:"🔑 Chave de API",apiKeyUnset:"definir",checking:"Verificando...",chooseLang:"Escolha seu idioma",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Acesso direto ao Claude. As chaves começam com",
  byokAnthS1:"Acesse console.anthropic.com",byokAnthS2:"Cadastre-se / faça login",byokAnthS3:"Configurações → Chaves de API → Criar chave",byokAnthLink:"Obter chave Anthropic →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Pague conforme o uso. Geralmente mais barato. As chaves começam com",
  byokOrS1:"Acesse openrouter.ai",byokOrS2:"Cadastre-se / faça login",byokOrS3:"Chaves → Criar chave",byokOrLink:"Obter chave OpenRouter →",
  keyErrFmt:"A chave deve começar com sk-ant- ou sk-or-",keyErrInv:"Chave inválida: ",keyErrNet:"Não foi possível verificar com a API — chave salva mesmo assim.",
  usageStat:"Estatísticas de uso",apiCalls:"Chamadas de API",estCost:"Custo estimado",inputTok:"Tokens de entrada",outputTok:"Tokens de saída",resetStats:"Resetar estatísticas",
  rmTip:"Remover",start:"Iniciar",cred:"créditos",credFree:"créditos grátis",credOut:"Sem créditos",
  credOutMsg:"Seus créditos gratuitos acabaram. Adicione sua própria chave de API para continuar — gratuita na Anthropic ou OpenRouter.",
  credByok:"Adicionar minha chave →",
  lp:["🧠 Pensando...","☕ Preparando ideias...","🔮 Bola de cristal aquecendo...","🧙 Lançando feitiços...","🤔 Pensamento profundo...","🎯 Focando..."],
  topUp:"Comprar créditos",topUpDesc:"10 créditos por €1,00",topUpBtn:"Pagar com Stripe →",
  topUpSuccess:"Pagamento realizado! Os créditos serão adicionados em breve.",topUpPending:"Processando créditos...",
  topUpPopupTitle:"Créditos adicionados! 🎉",
  topUpPopupMsg:"untangle.lol é gratuito e privado — sem anúncios, sem coleta de dados. Os créditos mantêm a IA funcionando e apoiam um produto justo e independente. Obrigado pelo seu apoio!",
  topUpPopupBtn:"Ótimo, vamos lá!",
  altruismPopupTitle:"Que gentileza! 💛",
  altruismPopupMsg:"Sua meta é ajudar outras pessoas — como voluntariado, cuidado ou apoio a uma boa causa. Isso merece recompensa: conclua todas as etapas e ganhe automaticamente 10 créditos grátis!",
  altruismPopupBtn:"Ótimo, vamos lá!",
  altruismBonusTitle:"🎁 +10 créditos ganhos!",
  altruismBonusMsg:"Parabéns! Você concluiu sua meta altruísta. Como agradecimento pelo seu esforço em ajudar os outros, adicionamos 10 créditos grátis à sua conta.",
  altruismBonusBtn:"Incrível, obrigado!",
  altruismTeaser:"💛 Sua meta é ajudar outras pessoas? Então ganhe 10 créditos grátis ao concluir todas as etapas.",
  altruismPopupMsgRepeat:"Sua meta é ajudar outras pessoas — o que é verdadeiramente maravilhoso. Conclua todas as etapas e faça uma diferença real!",
  analyticsNote:"Coletamos estatísticas de uso anônimas (sem cookies, sem dados pessoais).",
  signIn:"Entrar com Google",signInSub:"Salve suas metas em todos os dispositivos",signOut:"Sair",
  profile:"Perfil",terms:"Termos",privacy:"Privacidade",stats:"Estatísticas",donate:"❤️ Doar",
  share:"Compartilhar",shareCopy:"Copiar",shareCopied:"Copiado!",shareMsg:"Veja meu plano de ação no untangle.lol:",
  altruismLoadingMsg:"💛 Você está fazendo algo maravilhoso pelos outros.",
  altruisticSugg:["Quero fazer voluntariado em um banco de alimentos","Quero cuidar de um familiar","Quero ser mentor de um jovem","Quero doar sangue regularmente","Quero criar uma horta comunitária"],
  phSugg:["Quero dormir melhor","Quero aprender guitarra","Quero me exercitar todos os dias","Quero escrever um livro","Quero me alimentar de forma mais saudável"],
  woop:"🎯 Experimentar WOOP",woopOr:"ou",woopTitle:"Método WOOP",
  woopSub:"Uma técnica comprovada para transformar desejos em ações — passo a passo.",
  woopLabels:["Desejo","Resultado","Obstáculo","Plano"],
  woopHints:[
    "O que você realmente quer? Escolha algo que toque seu coração — desafiador, mas alcançável.",
    "Imagine o melhor resultado possível. Como você se sente quando seu desejo se realiza?",
    "Qual é o principal obstáculo interno — um hábito, sentimento ou pensamento — que poderia te impedir?",
    "Se [obstáculo], então farei [ação]. Crie um plano concreto se-então.",
  ],
  woopPh:[
    "Ex.: 'Quero me exercitar toda manhã'",
    "Ex.: 'Me sinto cheio de energia e orgulhoso de mim mesmo'",
    "Ex.: 'Desligo o alarme porque estou cansado'",
    "Ex.: 'Se eu desligar o alarme, separo a roupa de treino na noite anterior'",
  ],
  woopGo:"Criar meu plano →",woopLink:"Saiba mais sobre a ciência",woopSummaryTitle:"Seu WOOP",
  suggLabel:"💡 Escolha uma sugestão",
  taClrConfirm:"limpar?",
  celebTitle:"Parabéns! 🎉",
  celebMsg:"Você concluiu todas as etapas. Muito bem — isso merece comemoração!",
  celebBtn:"Obrigado!",
};
export default pt;
