const sw = {
  code:"sw",label:"Kiswahili",flag:"🇰🇪",
  ph:"Mf. 'Nataka kulala vizuri' au 'Nataka kujifunza gitaa' 🎸",
  hero:"Unataka kufikia nini?",
  heroS:["Andika tu.","Hakuna swali la ajabu.","Kubwa au dogo — chochote kinafaa.","Unafikiri nini?","Andika, tutakusaidia kusonga mbele."],
  go:"Tuanze →",back:"← Rudi",out:"Toka",clr:"🗑️ Futa yote",nG:"➕ Lengo jipya",noG:"Bado hakuna malengo. Ni wakati wa kuanza!",
  prog:"maendeleo",allD:"🎉 Yote yamekamilika!",sOf:"kati ya",
  eth:"🌍 Ushauri kwa heshima kwa watu, sayari na ustawi",
  err:"Samahani, jaribu tena!",resB:"← Rudi kwenye muhtasari",dW:"Karibu tena",dS:"Haya ndio malengo yako.",
  byok:"Ingiza ufunguo wa API",byokH1:"Tumia ufunguo wako wa API",chAuth:"Badilisha uthibitishaji",rmKey:"Ondoa ufunguo",lSel:"Lugha",
  byokL:"Ufunguo wa API (Anthropic au OpenRouter)",byokPh:"sk-ant-... au sk-or-...",byokSave:"Hifadhi & endelea",
  byokNote:"Imehifadhiwa kwenye kivinjari chako tu. Haishirikishwi kamwe.",
  apiKeyBadge:"🔑 Ufunguo wa API",apiKeyUnset:"weka",checking:"Inakagua...",chooseLang:"Chagua lugha yako",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Ufikiaji wa moja kwa moja wa Claude. Funguo zinaanza na",
  byokAnthS1:"Nenda kwa console.anthropic.com",byokAnthS2:"Jisajili / ingia",byokAnthS3:"Mipangilio → Funguo za API → Unda ufunguo",byokAnthLink:"Pata ufunguo wa Anthropic →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Lipa kadri unavyotumia. Mara nyingi ni nafuu zaidi. Funguo zinaanza na",
  byokOrS1:"Nenda kwa openrouter.ai",byokOrS2:"Jisajili / ingia",byokOrS3:"Funguo → Unda ufunguo",byokOrLink:"Pata ufunguo wa OpenRouter →",
  keyErrFmt:"Ufunguo lazima uanze na sk-ant- au sk-or-",keyErrInv:"Ufunguo batili: ",keyErrNet:"Imeshindwa kuthibitisha na API — ufunguo umehifadhiwa hata hivyo.",
  usageStat:"Takwimu za matumizi",apiCalls:"Simu za API",estCost:"Gharama inayokadiriwa",inputTok:"Tokeni za pembejeo",outputTok:"Tokeni za matokeo",resetStats:"Weka upya takwimu",
  rmTip:"Ondoa",start:"Anza",cred:"mikopo",credFree:"mikopo ya bure",credOut:"Mikopo imeisha",
  credOutMsg:"Mikopo yako ya bure imeisha. Ongeza ufunguo wako wa API ili kuendelea — bure kutoka Anthropic au OpenRouter.",
  credByok:"Ongeza ufunguo wako →",
  lp:["🧠 Nafikiri...","☕ Ninatengeneza mawazo...","🔮 Mpira wa kioo unawaka...","🧙 Ninafanya uchawi...","🤔 Mawazo ya kina...","🎯 Ninalenga..."],
  topUp:"Ongeza mikopo",topUpDesc:"Mikopo 10 kwa €1.00",topUpBtn:"Lipa na Stripe →",
  topUpSuccess:"Malipo yamefanikiwa! Mikopo itaongezwa hivi karibuni.",topUpPending:"Inashughulikia mikopo...",
  topUpPopupTitle:"Mikopo imeongezwa! 🎉",
  topUpPopupMsg:"untangle.lol ni bure na ya faragha — hakuna matangazo, hakuna kukusanya data. Mikopo inaweka AI ikifanya kazi na inasaidia bidhaa ya haki na huru. Asante!",
  topUpPopupBtn:"Vizuri, tuanze!",
  altruismPopupTitle:"Una huruma sana! 💛",
  altruismPopupMsg:"Lengo lako kuhusu kusaidia wengine — kama kujitolea, kutunza, au kusaidia sababu nzuri. Hii inastahili tuzo: kamilisha hatua zote na upate mikopo 10 ya bure kiotomatiki!",
  altruismPopupBtn:"Vizuri, tuanze!",
  altruismBonusTitle:"🎁 +10 mikopo imepatikana!",
  altruismBonusMsg:"Hongera! Umekamilisha lengo lako la kujitolea. Kama shukrani kwa juhudi zako za kusaidia wengine, tumeongeza mikopo 10 ya bure kwenye akaunti yako.",
  altruismBonusBtn:"Ajabu, asante!",
  altruismTeaser:"💛 Unataka kusaidia wengine? Ingiza lengo la kujitolea na upate mikopo 10 ya bure ukikamilisha hatua zote.",
  altruismPopupMsgRepeat:"Lengo lako kuhusu kusaidia wengine — ambayo ni ya kupendeza kweli kweli. Kamilisha hatua zote na fanya tofauti halisi!",
  analyticsNote:"Tunakusanya takwimu za matumizi zisizo na jina (hakuna vidakuzi, hakuna data ya kibinafsi).",
  signIn:"Ingia na Google",signInSub:"Hifadhi malengo yako kwenye vifaa vyote",signOut:"Toka",
  profile:"Wasifu",terms:"Masharti",privacy:"Faragha",stats:"Takwimu",donate:"❤️ Changia",revenue:"Mapato",
  share:"Shiriki",shareCopy:"Nakili",shareCopied:"Imenakiliwa!",shareMsg:"Angalia mpango wangu wa hatua kwenye untangle.lol:",
  altruismLoadingMsg:"💛 Unafanya kitu cha ajabu kwa wengine.",
  altruisticSugg:["Nataka kujitolea kwenye benki ya chakula","Nataka kuwa mtunzaji wa mwanafamilia","Nataka kuwa mshauri kwa kijana","Nataka kutoa damu mara kwa mara","Nataka kuanzisha bustani ya jamii"],
  phSugg:["Nataka kulala vizuri","Nataka kujifunza gitaa","Nataka kufanya mazoezi kila siku","Nataka kuandika kitabu","Nataka kula vyakula vya afya"],
  woop:"🎯 Jaribu WOOP",woopOr:"au",woopTitle:"Njia ya WOOP",
  woopSub:"Mbinu iliyothibitishwa ya kubadilisha matakwa kuwa vitendo — hatua kwa hatua.",
  woopLabels:["Tamaa","Matokeo","Kikwazo","Mpango"],
  woopHints:[
    "Unataka nini kweli kweli? Chagua kitu kinachogusa moyo wako — changamoto lakini inayoweza kufikiwa.",
    "Fikiria matokeo bora iwezekanavyo. Utahisi vipi tamaa yako ikitimia?",
    "Kikwazo kikuu cha ndani ni nini — tabia, hisia, au mawazo — ambacho kinaweza kukuzuia?",
    "Ikiwa [kikwazo], basi nitafanya [hatua]. Tengeneza mpango maalum wa ikiwa-basi.",
  ],
  woopPh:[
    "Mf. 'Nataka kufanya mazoezi kila asubuhi'",
    "Mf. 'Nahisi nguvu na kujivunia mwenyewe'",
    "Mf. 'Ninazima kengele kwa sababu nimechoka'",
    "Mf. 'Ikiwa ninazima kengele, nitaweka nguo za mazoezi usiku uliopita'",
  ],
  woopGo:"Unda mpango wangu →",woopLink:"Jifunze kuhusu sayansi",woopSummaryTitle:"WOOP yako",
  suggLabel:"💡 Chagua pendekezo",
  taClrConfirm:"futa?",
  celebTitle:"Hongera! 🎉",
  celebMsg:"Umekamilisha hatua zote. Vizuri sana — hii inastahili kusherehekewa!",
  celebBtn:"Asante!",
};
export default sw;
