const sw = {
  code:"sw",label:"Kiswahili",flag:"🇰🇪",
  ph:"Anza kuandika...",
  hero:"Unataka kufikia nini?",heroLabel:"Andika hapa kinachokusumbua",
  heroS:["Andika tu.","Hakuna swali la ajabu.","Kubwa au dogo — chochote kinafaa.","Unafikiri nini?","Andika, tutakusaidia kusonga mbele."],
  go:"Tuanze →",back:"Rudi",out:"Toka",clr:"Futa yote",nG:"Lengo jipya",noG:"Bado hakuna malengo. Ni wakati wa kuanza!",
  prog:"maendeleo",allD:"Yote yamekamilika!",sOf:"kati ya",
  eth:"Ushauri kwa heshima kwa watu, sayari na ustawi",
  err:"Samahani, jaribu tena!",resB:"← Rudi kwenye muhtasari",dW:"Karibu tena",dS:"Haya ndio malengo yako.",
  byok:"Ingiza ufunguo wa API",byokH1:"Tumia ufunguo wako wa API",chAuth:"Badilisha uthibitishaji",rmKey:"Ondoa ufunguo",lSel:"Lugha",
  byokL:"Ufunguo wa API (Anthropic au OpenRouter)",byokPh:"sk-ant-... au sk-or-...",byokSave:"Hifadhi & endelea",
  byokNote:"Imehifadhiwa kwenye kivinjari chako tu. Haishirikishwi kamwe.",
  apiKeyBadge:"Ufunguo wa API",apiKeyUnset:"weka",checking:"Inakagua...",chooseLang:"Chagua lugha yako",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Ufikiaji wa moja kwa moja wa Claude. Funguo zinaanza na",
  byokAnthS1:"Nenda kwa console.anthropic.com",byokAnthS2:"Jisajili / ingia",byokAnthS3:"Mipangilio → Funguo za API → Unda ufunguo",byokAnthLink:"Pata ufunguo wa Anthropic →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Lipa kadri unavyotumia. Mara nyingi ni nafuu zaidi. Funguo zinaanza na",
  byokOrS1:"Nenda kwa openrouter.ai",byokOrS2:"Jisajili / ingia",byokOrS3:"Funguo → Unda ufunguo",byokOrLink:"Pata ufunguo wa OpenRouter →",
  keyErrFmt:"Ufunguo lazima uanze na sk-ant- au sk-or-",keyErrInv:"Ufunguo batili: ",keyErrNet:"Imeshindwa kuthibitisha na API — ufunguo umehifadhiwa hata hivyo.",
  usageStat:"Takwimu za matumizi",apiCalls:"Simu za API",estCost:"Gharama inayokadiriwa",inputTok:"Tokeni za pembejeo",outputTok:"Tokeni za matokeo",resetStats:"Weka upya takwimu",
  rmTip:"Ondoa",start:"Anza",cred:"maswali",credFree:"maswali ya bure",credOut:"Maswali yameisha",
  credOutMsg:"Maswali yako ya bure yameisha. Ongeza ufunguo wako wa API ili kuendelea — bure kutoka Anthropic au OpenRouter.",
  credByok:"Ongeza ufunguo wako →",
  lp:["Nafikiri...","Ninatengeneza mawazo...","Mpira wa kioo unawaka...","Ninafanya uchawi...","Mawazo ya kina...","Ninalenga..."],
  topUpDesc:"Maswali 10 kwa €2.50",topUpBtn:"Lipa na Stripe →",
  topUpSuccess:"Malipo yamefanikiwa! Maswali yataongezwa hivi karibuni.",topUpPending:"Inashughulikia maswali...",
  topUpPopupTitle:"Maswali yameongezwa!",
  topUpPopupMsg:"untangle.lol ni bure na ya faragha — hakuna matangazo, hakuna kukusanya data. Maswali yanaweka AI ikifanya kazi na inasaidia bidhaa ya haki na huru. Asante!",
  topUpPopupBtn:"Vizuri, tuanze!",
  altruismPopupTitle:"Una huruma sana!",
  altruismPopupMsg:"Lengo lako ni kwa wengine — shiriki mpango wako na upate maswali 2 bure.",
  altruismPopupBtn:"Shiriki mpango →",
  altruismBonusTitle:"+2 maswali yamepatikana!",
  altruismBonusMsg:"Umeshiriki mpango wako! Asante, hapa kuna maswali 2 bure.",
  altruismBonusBtn:"Ajabu, asante!",
  altruismTeaser:"Shiriki mpango kwa wengine na upate maswali 2 bure.",
  altruismPopupMsgRepeat:"Lengo lako linasaidia wengine — vizuri sana! Shiriki mpango wako na umhamasishe mtu.",
  altruismShareCta:"Shiriki mpango huu na upate +2 maswali bure",
  analyticsNote:"Tunakusanya takwimu za matumizi zisizo na jina (hakuna vidakuzi, hakuna data ya kibinafsi).",
  signIn:"Ingia na Google",signInSub:"Hifadhi malengo yako kwenye vifaa vyote",signOut:"Toka",
  profile:"Wasifu",terms:"Masharti",privacy:"Faragha",stats:"Takwimu",donate:"Changia",donateMsg:"Mchango wako unafanya dunia kuwa bora zaidi",revenue:"Mapato",revTotal:"Mapato yote",revEmpty:"Bado hakuna miamala.",revMore:"Pakia zaidi",
  share:"Shiriki",shareCopy:"Nakili",shareCopied:"Imenakiliwa!",shareMsg:"Angalia mpango wangu wa hatua kwenye untangle.lol:",
  altruismLoadingMsg:"Unafanya kitu cha ajabu kwa wengine.",
  altruisticSugg:["Nataka kujitolea kwenye benki ya chakula","Nataka kuwa mtunzaji wa mwanafamilia","Nataka kuwa mshauri kwa kijana","Nataka kutoa damu mara kwa mara","Nataka kuanzisha bustani ya jamii","Nataka kupanga mkusanyiko wa michango kwa ajili ya hisani","Nataka kusaidia wazee katika jirani zangu","Nataka kujitolea katika makazi ya wanyama","Nataka kuongeza ufahamu kuhusu mabadiliko ya tabianchi","Nataka kusaidia watu wazima kujifunza kusoma"],
  phSugg:["Nataka kulala vizuri","Nataka kujifunza gitaa","Nataka kufanya mazoezi kila siku","Nataka kuandika kitabu","Nataka kula vyakula vya afya","Nataka kujifunza lugha mpya","Nataka kutumia mitandao ya kijamii kidogo zaidi","Nataka kuanzisha biashara yangu","Nataka kutumia muda zaidi na familia yangu","Nataka kutafakari kila asubuhi","Nataka kulipa madeni yangu","Nataka kukimbia marathon","Nataka kujifunza kupika","Nataka kupata kazi mpya","Nataka kuhifadhi pesa zaidi"],
  woop:"Jaribu WOOP",woopOr:"au",woopTitle:"Njia ya WOOP",
  woopSub:"Mbinu iliyothibitishwa ya kubadilisha matakwa kuwa vitendo — hatua kwa hatua.",
  woopLabels:["Tamaa","Matokeo","Kikwazo","Mpango"],
  woopHints:[
    "Unataka nini kweli kweli? Chagua kitu kinachogusa moyo wako — changamoto lakini inayoweza kufikiwa.",
    "Fikiria matokeo bora iwezekanavyo. Utahisi vipi tamaa yako ikitimia?",
    "Kikwazo kikuu cha ndani ni nini — tabia, hisia, au mawazo — ambacho kinaweza kukuzuia?",
    "Ikiwa [kikwazo], basi nitafanya [hatua]. Tengeneza mpango maalum wa ikiwa-basi.",
  ],
  woopPh:[
    "Mf. 'Nataka kufanya mazoezi kila asubuhi'",
    "Mf. 'Nahisi nguvu na kujivunia mwenyewe'",
    "Mf. 'Ninazima kengele kwa sababu nimechoka'",
    "Mf. 'Ikiwa ninazima kengele, nitaweka nguo za mazoezi usiku uliopita'",
  ],
  woopGo:"Unda mpango wangu →",woopLink:"Jifunze kuhusu sayansi",woopSummaryTitle:"WOOP yako",
  suggLabel:"Hujui cha kuandika? Chagua pendekezo hapa chini",
  recentQ:"Maswali ya hivi karibuni",
  taClrConfirm:"futa?",
  celebTitle:"Hongera!",
  celebMsg:"Umekamilisha hatua zote. Vizuri sana — hii inastahili kusherehekewa!",
  celebBtn:"Asante!",
  fbTitle:"Maoni",fbPh:"Kuna hitilafu au mapendekezo? Tuambie…",fbSend:"Tuma",fbCancel:"Ghairi",fbSent:"Imepokelewa, asante!",fbErr:"Imeshindwa — jaribu tena",fbHint:"⌘↵ kutuma",
  dyslexia:"Fonti rafiki kwa dyslexia",
  payTitle:"Pata maswali zaidi",
  paySubtitle:"Kila swali linaunda mpango kamili wa hatua wa AI",
  payLoginRequired:"Ingia ili kununua maswali",
  payLoginDesc:"Fungua akaunti ya bure ili kununua maswali na kuyahifadhi kwenye vifaa vyako vyote.",
  paySecure:"Malipo salama kupitia Stripe & Mollie",
  perQ:"/ swali",
  tierStarter:"Mwanzo",
  tierPopular:"Maarufu",
  tierPower:"Pro",
  tierCustom:"Maalum",
  tierCustomLabel:"Idadi ya maswali (angalau 50)",
  tierBadge:"Maarufu zaidi",
  settingsTitle:"Akaunti & maswali",
  topUp:"Nunua maswali",
  howToUse:"Jinsi inavyofanya kazi",
  remaining:"zilizobaki",
  fbPageDesc:"Kuna kitu kinachokosekana, au una pendekezo? Tunasoma kila ujumbe na kutumia maoni yako kuboresha untangle.lol kwa kila mtu.",
  dWName:"Karibu tena, {name}!",
  madeBy:"Imewezeshwa na Bach Software",
};
export default sw;
