const tr = {
  code:"tr",label:"Türkçe",flag:"🇹🇷",
  ph:"Örn. 'Daha iyi uyumak istiyorum' veya 'Gitar öğrenmek istiyorum' 🎸",
  hero:"Ne başarmak istiyorsunuz?",
  heroS:["Sadece yazın.","Hiçbir soru garip değil.","Büyük veya küçük — her şey olabilir.","Aklınızda ne var?","Yazın, ilerlemenize yardımcı olalım."],
  go:"Başlayalım →",back:"← Geri",out:"Çıkış yap",clr:"🗑️ Tümünü temizle",nG:"➕ Yeni hedef",noG:"Henüz hedef yok. Başlama zamanı!",
  prog:"ilerleme",allD:"🎉 Tümü tamamlandı!",sOf:"/",
  eth:"🌍 İnsana, gezegene ve esenliğe saygıyla tavsiyeler",
  err:"Ups, tekrar dene!",resB:"← Özete geri dön",dW:"Tekrar hoş geldiniz",dS:"İşte hedefleriniz.",
  byok:"API anahtarı girin",byokH1:"Kendi API anahtarınızı kullanın",chAuth:"Kimlik doğrulamayı değiştir",rmKey:"Anahtarı kaldır",lSel:"Dil",
  byokL:"API Anahtarı (Anthropic veya OpenRouter)",byokPh:"sk-ant-... veya sk-or-...",byokSave:"Kaydet ve devam et",
  byokNote:"Yalnızca tarayıcınızda saklanır. Asla paylaşılmaz.",
  apiKeyBadge:"🔑 API Anahtarı",apiKeyUnset:"ayarla",checking:"Kontrol ediliyor...",chooseLang:"Dilinizi seçin",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Claude'a doğrudan erişim. Anahtarlar şununla başlar",
  byokAnthS1:"console.anthropic.com adresine gidin",byokAnthS2:"Kaydolun / giriş yapın",byokAnthS3:"Ayarlar → API Anahtarları → Anahtar oluştur",byokAnthLink:"Anthropic anahtarı al →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Kullandıkça öde. Genellikle daha ucuz. Anahtarlar şununla başlar",
  byokOrS1:"openrouter.ai adresine gidin",byokOrS2:"Kaydolun / giriş yapın",byokOrS3:"Anahtarlar → Anahtar oluştur",byokOrLink:"OpenRouter anahtarı al →",
  keyErrFmt:"Anahtar sk-ant- veya sk-or- ile başlamalıdır",keyErrInv:"Geçersiz anahtar: ",keyErrNet:"API ile doğrulanamadı — anahtar yine de kaydedildi.",
  usageStat:"Kullanım istatistikleri",apiCalls:"API çağrıları",estCost:"Tahmini maliyet",inputTok:"Girdi tokenleri",outputTok:"Çıktı tokenleri",resetStats:"İstatistikleri sıfırla",
  rmTip:"Kaldır",start:"Başla",cred:"kredi",credFree:"ücretsiz kredi",credOut:"Kredi bitti",
  credOutMsg:"Ücretsiz krediniz bitti. Devam etmek için kendi API anahtarınızı ekleyin — Anthropic veya OpenRouter'dan ücretsiz alabilirsiniz.",
  credByok:"Kendi anahtarımı ekle →",
  lp:["🧠 Düşünüyorum...","☕ Fikirler demleniyor...","🔮 Kristal küre ısınıyor...","🧙 Büyü yapılıyor...","🤔 Derin düşünce...","🎯 Odaklanıyorum..."],
  topUp:"Kredi yükle",topUpDesc:"€2,50 için 10 kredi",topUpBtn:"Stripe ile öde →",
  topUpSuccess:"Ödeme başarılı! Kredi yakında eklenecek.",topUpPending:"Kredi işleniyor...",
  topUpPopupTitle:"Kredi eklendi! 🎉",
  topUpPopupMsg:"untangle.lol ücretsiz ve özeldir — reklam yok, veri toplama yok. Krediler yapay zekayı çalıştırır ve adil, bağımsız bir ürünü destekler. Teşekkür ederiz!",
  topUpPopupBtn:"Harika, hadi başlayalım!",
  altruismPopupTitle:"Ne kadar naziksiniz! 💛",
  altruismPopupMsg:"Hedefiniz başkalarına yardım etmekle ilgili — gönüllülük, bakım veya iyi bir amacı destekleme gibi. Bu bir ödülü hak ediyor: tüm adımları tamamlayın ve otomatik olarak 10 ücretsiz kredi kazanın!",
  altruismPopupBtn:"Harika, hadi başlayalım!",
  altruismBonusTitle:"🎁 +10 kredi kazanıldı!",
  altruismBonusMsg:"Tebrikler! Özgecil hedefinizi tamamladınız. Başkalarına yardım etme çabanız için teşekkür olarak hesabınıza 10 ücretsiz kredi ekledik.",
  altruismBonusBtn:"Harika, teşekkürler!",
  altruismTeaser:"💛 Başkalarına yardım etmek ister misin? Özgecil bir hedef gir ve tüm adımları tamamlayarak 10 ücretsiz kredi kazan.",
  altruismPopupMsgRepeat:"Hedefiniz başkalarına yardım etmekle ilgili — bu gerçekten harika. Tüm adımları tamamlayın ve gerçek bir fark yaratın!",
  analyticsNote:"Anonim kullanım istatistikleri topluyoruz (çerez yok, kişisel veri yok).",
  signIn:"Google ile giriş yap",signInSub:"Hedeflerinizi tüm cihazlarınızda kaydedin",signOut:"Çıkış yap",
  profile:"Profil",terms:"Koşullar",privacy:"Gizlilik",stats:"İstatistikler",donate:"❤️ Bağış yap",revenue:"Gelir",revTotal:"Toplam gelir",revEmpty:"Henüz işlem yok.",revMore:"Daha fazla yükle",
  share:"Paylaş",shareCopy:"Kopyala",shareCopied:"Kopyalandı!",shareMsg:"untangle.lol'daki eylem planıma göz atın:",
  altruismLoadingMsg:"💛 Başkaları için harika bir şey yapıyorsunuz.",
  altruisticSugg:["Bir gıda bankasında gönüllü olmak istiyorum","Bir aile üyesine bakıcı olmak istiyorum","Bir gence rehberlik etmek istiyorum","Düzenli kan bağışlamak istiyorum","Bir toplum bahçesi başlatmak istiyorum"],
  phSugg:["Daha iyi uyumak istiyorum","Gitar öğrenmek istiyorum","Her gün spor yapmak istiyorum","Kitap yazmak istiyorum","Daha sağlıklı beslenmek istiyorum"],
  woop:"🎯 WOOP'u dene",woopOr:"veya",woopTitle:"WOOP Yöntemi",
  woopSub:"Dilekleri eyleme dönüştürmek için kanıtlanmış bir teknik — adım adım.",
  woopLabels:["Dilek","Sonuç","Engel","Plan"],
  woopHints:[
    "Gerçekten ne istiyorsunuz? Kalbinize dokunan bir şey seçin — zorlu ama ulaşılabilir.",
    "En iyi olası sonucu hayal edin. Dileğiniz gerçekleştiğinde nasıl hissedeceksiniz?",
    "Sizi engelleyebilecek temel iç engel nedir — bir alışkanlık, duygu veya düşünce?",
    "Eğer [engel] olursa, [eylem] yapacağım. Belirli bir eğer-o zaman planı oluşturun.",
  ],
  woopPh:[
    "Örn. 'Her sabah egzersiz yapmak istiyorum'",
    "Örn. 'Kendimi enerjik ve gurur dolu hissediyorum'",
    "Örn. 'Yorgun olduğum için alarmı kapatıyorum'",
    "Örn. 'Alarmı kapatırsam, önceki gece spor kıyafetlerimi hazırlayacağım'",
  ],
  woopGo:"Planımı oluştur →",woopLink:"Bilim hakkında öğren",woopSummaryTitle:"Senin WOOP'un",
  suggLabel:"💡 Öneri seç",
  taClrConfirm:"temizle?",
  celebTitle:"Tebrikler! 🎉",
  celebMsg:"Tüm adımları tamamladınız. Aferin — bu kutlamayı hak ediyor!",
  celebBtn:"Teşekkürler!",
};
export default tr;
