const tr = {
  code:"tr",label:"Türkçe",flag:"🇹🇷",
  ph:"Yazmaya başlayın...",
  hero:"Ne başarmak istiyorsunuz?",heroLabel:"Aklındakileri buraya yaz",
  heroS:["Sadece yazın.","Hiçbir soru garip değil.","Büyük veya küçük — her şey olabilir.","Aklınızda ne var?","Yazın, ilerlemenize yardımcı olalım."],
  go:"Başlayalım →",back:"Geri",out:"Çıkış yap",clr:"Tümünü temizle",nG:"Yeni hedef",noG:"Henüz hedef yok. Başlama zamanı!",
  prog:"ilerleme",allD:"Tümü tamamlandı!",sOf:"/",
  eth:"İnsana, gezegene ve esenliğe saygıyla tavsiyeler",
  err:"Ups, tekrar dene!",resB:"← Özete geri dön",dW:"Tekrar hoş geldiniz",dS:"İşte hedefleriniz.",
  byok:"API anahtarı girin",byokH1:"Kendi API anahtarınızı kullanın",chAuth:"Kimlik doğrulamayı değiştir",rmKey:"Anahtarı kaldır",lSel:"Dil",
  byokL:"API Anahtarı (Anthropic veya OpenRouter)",byokPh:"sk-ant-... veya sk-or-...",byokSave:"Kaydet ve devam et",
  byokNote:"Yalnızca tarayıcınızda saklanır. Asla paylaşılmaz.",
  apiKeyBadge:"API Anahtarı",apiKeyUnset:"ayarla",checking:"Kontrol ediliyor...",chooseLang:"Dilinizi seçin",
  byokAnthTitle:"Anthropic",byokAnthDesc:"Claude'a doğrudan erişim. Anahtarlar şununla başlar",
  byokAnthS1:"console.anthropic.com adresine gidin",byokAnthS2:"Kaydolun / giriş yapın",byokAnthS3:"Ayarlar → API Anahtarları → Anahtar oluştur",byokAnthLink:"Anthropic anahtarı al →",
  byokOrTitle:"OpenRouter",byokOrDesc:"Kullandıkça öde. Genellikle daha ucuz. Anahtarlar şununla başlar",
  byokOrS1:"openrouter.ai adresine gidin",byokOrS2:"Kaydolun / giriş yapın",byokOrS3:"Anahtarlar → Anahtar oluştur",byokOrLink:"OpenRouter anahtarı al →",
  keyErrFmt:"Anahtar sk-ant- veya sk-or- ile başlamalıdır",keyErrInv:"Geçersiz anahtar: ",keyErrNet:"API ile doğrulanamadı — anahtar yine de kaydedildi.",
  usageStat:"Kullanım istatistikleri",apiCalls:"API çağrıları",estCost:"Tahmini maliyet",inputTok:"Girdi tokenleri",outputTok:"Çıktı tokenleri",resetStats:"İstatistikleri sıfırla",
  rmTip:"Kaldır",start:"Başla",cred:"soru",credFree:"ücretsiz soru",credOut:"Soru bitti",
  credOutMsg:"Ücretsiz sorularınız bitti. Devam etmek için kendi API anahtarınızı ekleyin — Anthropic veya OpenRouter'dan ücretsiz alabilirsiniz.",
  credByok:"Kendi anahtarımı ekle →",
  lp:["Düşünüyorum...","Fikirler demleniyor...","Kristal küre ısınıyor...","Büyü yapılıyor...","Derin düşünce...","Odaklanıyorum..."],
  topUpDesc:"€2,50 için 10 soru",topUpBtn:"Stripe ile öde →",
  topUpSuccess:"Ödeme başarılı! Sorular yakında eklenecek.",topUpPending:"Sorular işleniyor...",
  topUpPopupTitle:"Sorular eklendi!",
  topUpPopupMsg:"untangle.lol ücretsiz ve özeldir — reklam yok, veri toplama yok. Sorular yapay zekayı çalıştırır ve adil, bağımsız bir ürünü destekler. Teşekkür ederiz!",
  topUpPopupBtn:"Harika, hadi başlayalım!",
  altruismPopupTitle:"Ne kadar naziksiniz!",
  altruismPopupMsg:"Hedefin başkaları için — planını paylaş ve 2 ücretsiz soru kazan.",
  altruismPopupBtn:"Planı paylaş →",
  altruismBonusTitle:"+{n} soru kazanıldı!",altruismBonusTitleSg:"+1 soru kazanıldı!",
  altruismBonusMsg:"Planını paylaştın! Teşekkür olarak 2 ücretsiz soru kazandın.",
  altruismBonusBtn:"Harika, teşekkürler!",
  altruismTeaser:"Başkaları için plan paylaş ve 2 ücretsiz soru kazan.",
  altruismPopupMsgRepeat:"Hedefin başkalarına yardımcı oluyor — harika! Planını paylaş ve birini ilhamlandır.",
  altruismShareCta:"Bu planı paylaş ve +2 ücretsiz soru kazan",
  analyticsNote:"Anonim kullanım istatistikleri topluyoruz (çerez yok, kişisel veri yok).",
  signIn:"Giriş yap",signInSub:"Hedeflerinizi tüm cihazlarınızda kaydedin",signOut:"Çıkış yap",
  profile:"Profil",terms:"Koşullar",privacy:"Gizlilik",stats:"İstatistikler",donate:"Bağış yap",donateMsg:"Bağışınız dünyayı biraz daha iyi yapar",revenue:"Gelir",revTotal:"Toplam gelir",revEmpty:"Henüz işlem yok.",revMore:"Daha fazla yükle",
  share:"Paylaş",shareCopy:"Kopyala",shareCopied:"Kopyalandı!",shareMsg:"untangle.lol'daki eylem planıma göz atın:",
  altruismLoadingMsg:"Başkaları için harika bir şey yapıyorsunuz.",
  altruisticSugg:["Bir gıda bankasında gönüllü olmak istiyorum","Bir aile üyesine bakıcı olmak istiyorum","Bir gence rehberlik etmek istiyorum","Düzenli kan bağışlamak istiyorum","Bir toplum bahçesi başlatmak istiyorum","Yardım amaçlı bağış kampanyası düzenlemek istiyorum","Komşu yaşlılara yardım etmek istiyorum","Hayvan barınağında gönüllü olmak istiyorum","İklim değişikliği farkındalığı oluşturmak istiyorum","Yetişkinlerin okuma öğrenmesine yardımcı olmak istiyorum"],
  phSugg:["Daha iyi uyumak istiyorum","Gitar öğrenmek istiyorum","Her gün spor yapmak istiyorum","Kitap yazmak istiyorum","Daha sağlıklı beslenmek istiyorum","Yeni bir dil öğrenmek istiyorum","Sosyal medyayı daha az kullanmak istiyorum","Kendi işimi kurmak istiyorum","Ailemle daha fazla zaman geçirmek istiyorum","Her sabah meditasyon yapmak istiyorum","Borçlarımı ödemek istiyorum","Bir maraton koşmak istiyorum","Yemek pişirmeyi öğrenmek istiyorum","Yeni bir iş bulmak istiyorum","Daha fazla para biriktirmek istiyorum"],
  woop:"WOOP'u dene",woopOr:"veya",woopTitle:"WOOP Yöntemi",
  woopSub:"Dilekleri eyleme dönüştürmek için kanıtlanmış bir teknik — adım adım.",
  woopLabels:["Dilek","Sonuç","Engel","Plan"],
  woopHints:[
    "Gerçekten ne istiyorsunuz? Kalbinize dokunan bir şey seçin — zorlu ama ulaşılabilir.",
    "En iyi olası sonucu hayal edin. Dileğiniz gerçekleştiğinde nasıl hissedeceksiniz?",
    "Sizi engelleyebilecek temel iç engel nedir — bir alışkanlık, duygu veya düşünce?",
    "Eğer [engel] olursa, [eylem] yapacağım. Belirli bir eğer-o zaman planı oluşturun.",
  ],
  woopPh:[
    "Örn. 'Her sabah egzersiz yapmak istiyorum'",
    "Örn. 'Kendimi enerjik ve gurur dolu hissediyorum'",
    "Örn. 'Yorgun olduğum için alarmı kapatıyorum'",
    "Örn. 'Alarmı kapatırsam, önceki gece spor kıyafetlerimi hazırlayacağım'",
  ],
  woopGo:"Planımı oluştur →",woopLink:"Bilim hakkında öğren",woopSummaryTitle:"Senin WOOP'un",
  suggLabel:"Ne yazacağını bilmiyor musun? Aşağıdan bir öneri seç",
  recentQ:"Son sorular",
  taClrConfirm:"temizle?",
  celebTitle:"Tebrikler!",
  celebMsg:"Tüm adımları tamamladınız. Aferin — bu kutlamayı hak ediyor!",
  celebBtn:"Teşekkürler!",
  fbTitle:"Geri bildirim",fbPh:"Bir sorun mu var yoksa öneri mi? Bize söyleyin…",fbSend:"Gönder",fbCancel:"İptal",fbSent:"Alındı, teşekkürler!",fbErr:"Başarısız — tekrar deneyin",fbHint:"⌘↵ göndermek için",
  dyslexia:"Disleksi dostu yazı tipi",
  payTitle:"Daha fazla soru al",
  paySubtitle:"Her soru eksiksiz bir yapay zeka eylem planı oluşturur",
  payLoginRequired:"Soru satın almak için giriş yapın",
  payLoginDesc:"Soru satın almak ve tüm cihazlarınızda saklamak için ücretsiz bir hesap oluşturun.",
  paySecure:"Stripe & Mollie aracılığıyla güvenli ödeme",
  perQ:"/ soru",
  tierStarter:"Başlangıç",
  tierPopular:"Popüler",
  tierPower:"Pro",
  tierCustom:"Özel",
  tierCustomLabel:"Soru sayısı (min. 50)",
  tierBadge:"En popüler",
  settingsTitle:"Hesap & sorular",
  topUp:"Soru satın al",
  howToUse:"Nasıl çalışır",
  remaining:"kalan",
  fbPageDesc:"Bir şey çalışmıyor mu, yoksa bir öneriniz mi var? Her mesajı okuyoruz ve geri bildiriminizi herkes için untangle.lol'u daha iyi hale getirmek için kullanıyoruz.",
  dWName:"Tekrar hoş geldiniz, {name}!",
  pageTitle:"untangle.lol — Ücretsiz Yapay Zeka Hedef Planlayıcı",
  madeBy:"Bach Software tarafından mümkün kılındı",
  magicOr:"veya",magicPh:"your@email.com",magicBtn:"Link gönder",
  magicSentTitle:"Gelen kutunu kontrol et",magicSentMsg:"Giriş bağlantısı gönderdik:",magicRetry:"Farklı adres kullan",
  magicError:"Bir şeyler yanlış gitti. Tekrar dene.",magicRateLimit:"Çok fazla deneme. Daha sonra tekrar dene.",
};
export default tr;
