const zh = {
  code:"zh",label:"中文",flag:"🇨🇳",
  ph:"开始输入...",
  hero:"你想实现什么？",heroLabel:"写下你心里的想法",
  heroS:["直接输入吧。","没有问题太奇怪。","大目标还是小目标——都可以。","你在想什么？","写下来，我们帮你理清。"],
  go:"开始 →",back:"← 返回",out:"退出登录",clr:"🗑️ 清除全部",nG:"➕ 新目标",noG:"还没有目标。是时候开始了！",
  prog:"进度",allD:"🎉 全部完成！",sOf:"共",
  eth:"🌍 尊重人、地球与健康的建议",
  err:"出错了，请重试！",resB:"← 返回概览",dW:"欢迎回来",dS:"这是你的目标。",
  byok:"输入 API 密钥",byokH1:"使用你自己的 API 密钥",chAuth:"更改验证方式",rmKey:"删除密钥",lSel:"语言",
  byokL:"API 密钥（Anthropic 或 OpenRouter）",byokPh:"sk-ant-... 或 sk-or-...",byokSave:"保存并继续",
  byokNote:"仅保存在你的浏览器中，从不共享。",
  apiKeyBadge:"🔑 API 密钥",apiKeyUnset:"设置",checking:"检查中...",chooseLang:"选择语言",
  byokAnthTitle:"Anthropic",byokAnthDesc:"直接访问 Claude。密钥以",
  byokAnthS1:"前往 console.anthropic.com",byokAnthS2:"注册 / 登录",byokAnthS3:"设置 → API 密钥 → 创建密钥",byokAnthLink:"获取 Anthropic 密钥 →",
  byokOrTitle:"OpenRouter",byokOrDesc:"按需付费，通常更便宜。密钥以",
  byokOrS1:"前往 openrouter.ai",byokOrS2:"注册 / 登录",byokOrS3:"密钥 → 创建密钥",byokOrLink:"获取 OpenRouter 密钥 →",
  keyErrFmt:"密钥应以 sk-ant- 或 sk-or- 开头",keyErrInv:"无效密钥：",keyErrNet:"无法连接 API 验证——密钥已保存。",
  usageStat:"使用统计",apiCalls:"API 调用次数",estCost:"预计费用",inputTok:"输入 Token",outputTok:"输出 Token",resetStats:"重置统计",
  rmTip:"删除",start:"开始",cred:"积分",credFree:"免费积分",credOut:"积分不足",
  credOutMsg:"你的免费积分已用完。添加自己的 API 密钥继续使用——可从 Anthropic 或 OpenRouter 免费获取。",
  credByok:"添加我的密钥 →",
  lp:["🧠 思考中...","☕ 整理想法...","🔮 水晶球预热中...","🧙 施展魔法...","🤔 深度思考...","🎯 锁定目标..."],
  topUp:"充值积分",topUpDesc:"€2.50 兑换 10 积分",topUpBtn:"通过 Stripe 付款 →",
  topUpSuccess:"支付成功！积分即将到账。",topUpPending:"处理积分中...",
  topUpPopupTitle:"积分已到账！🎉",
  topUpPopupMsg:"untangle.lol 免费且私密——没有广告，不收集数据。积分让 AI 持续运转，支持公平独立的产品。谢谢你的支持！",
  topUpPopupBtn:"太好了，开始吧！",
  altruismPopupTitle:"你真善良！💛",
  altruismPopupMsg:"你的目标是帮助他人——比如志愿服务、照顾他人或支持公益事业。这值得奖励：完成所有步骤，自动获得 3 个免费积分！",
  altruismPopupBtn:"太好了，开始吧！",
  altruismBonusTitle:"🎁 +3 积分已获得！",
  altruismBonusMsg:"恭喜！你完成了利他目标。为感谢你对他人的付出，我们为你的账户添加了 3 个免费积分。",
  altruismBonusBtn:"太棒了，谢谢！",
  altruismTeaser:"💛 为他人做点好事，赚取 3 个免费积分。",
  altruismPopupMsgRepeat:"你的目标是帮助他人——这真的很了不起。完成所有步骤，创造真正的改变！",
  analyticsNote:"我们收集匿名使用统计数据（无 Cookie，无个人数据）。",
  signIn:"使用 Google 登录",signInSub:"在所有设备上保存你的目标",signOut:"退出登录",
  profile:"个人资料",terms:"条款",privacy:"隐私",stats:"统计",donate:"❤️ 捐赠",donateMsg:"❤️ 您的捐赠让世界变得更美好",revenue:"收入",revTotal:"总收入",revEmpty:"暂无交易。",revMore:"加载更多",
  share:"分享",shareCopy:"复制",shareCopied:"已复制！",shareMsg:"查看我在 untangle.lol 上的行动计划：",
  altruismLoadingMsg:"💛 你正在为他人做一件美好的事。",
  altruisticSugg:["我想在食物银行做志愿者","我想照顾家人","我想成为年轻人的导师","我想定期献血","我想创建一个社区花园","我想组织慈善募款活动","我想帮助社区里的老年人","我想在动物收容所做志愿者","我想推动气候变化意识","我想帮助成年人学习阅读"],
  phSugg:["我想睡得更好","我想学吉他","我想每天运动","我想写一本书","我想吃得更健康","我想学一门新语言","我想减少使用社交媒体","我想创业","我想花更多时间陪家人","我想每天早上冥想","我想还清债务","我想跑一场马拉松","我想学做饭","我想找到新工作","我想多储蓄"],
  woop:"🎯 尝试 WOOP",woopOr:"或",woopTitle:"WOOP 方法",
  woopSub:"一种将愿望转化为行动的有效技巧——循序渐进。",
  woopLabels:["愿望","结果","障碍","计划"],
  woopHints:[
    "你真正想要什么？选择一件触动你内心的事——有挑战性但可实现。",
    "想象最好的结果。当愿望实现时，你有什么感受？",
    "最主要的内在障碍是什么——一种习惯、感受或想法——可能阻碍你？",
    "如果出现[障碍]，我将采取[行动]。制定一个具体的如果-那么计划。",
  ],
  woopPh:[
    "例如：'我想每天早上运动'",
    "例如：'我感到精力充沛，为自己感到骄傲'",
    "例如：'我因为疲惫而关掉闹钟'",
    "例如：'如果我关掉闹钟，我会在前一晚准备好运动服'",
  ],
  woopGo:"创建我的计划 →",woopLink:"了解相关科学",woopSummaryTitle:"你的 WOOP",
  suggLabel:"💡 选择建议",
  taClrConfirm:"清除？",
  celebTitle:"恭喜！🎉",
  celebMsg:"你已完成所有步骤。做得好——值得庆祝！",
  celebBtn:"谢谢！",
  fbTitle:"反馈",fbPh:"有什么问题或建议？请告诉我们…",fbSend:"发送",fbCancel:"取消",fbSent:"已收到，谢谢！",fbErr:"发送失败 — 请重试",fbHint:"⌘↵ 发送",
  dyslexia:"阅读障碍友好字体",
  braille:"盲文字体",
};
export default zh;
